<div id="formtabs">
	<ul>
		<li><a href="#tabs-0" >Metas</a></li>
	</ul>
	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'metas', 'action'=>'save'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->form->id ?>
			</div>
			<?php echo $this->form->objetivo_especifico_id;?>
			<?php echo $this->form->descricao;?>
			
			<?php echo $this->form->submit;?>
		</form>
		
	</div>
</div>
<a href='<?php echo $this->url(array('controller'=>'plano', 'action'=>'objetivos-especificos'))?>'>Voltar</a>

