<div id="formtabs">
    <ul>
        <li><a href="#tabs-0">Programa</a></li>
        <li><a href="#tabs-1">Objetivos</a></li>
    </ul>
    <div id="tabs-0" style="overflow: hidden">
        <form id='<?php echo $this->form->getId();?>'
              enctype='<?php echo $this->form->getEnctype();?>'
              action='<?php echo $this->url(array('controller' => 'programas', 'action' => 'save'));?>?format=json'
              method="post">
            <input type="hidden" id="dependents" value="1,2,3" />
            <div style='display: none'>
                <?php echo $this->form->programa->id ?>
            </div>
            <table width="100%" border="0">
                <tr>
                    <td>
<?php echo $this->form->programa->descricao; ?>
                    </td>
                </tr>
                <tr>
                    <td>
<?php echo $this->form->programa->menu; ?>
                    </td>
                </tr>
                <tr>
                    <td>
<?php echo $this->form->programa->meta; ?>
                    </td>
                </tr>
                <tr>
                    <td>
<?php echo $this->form->programa->interfaces; ?>
                    </td>
                </tr>
                <tr>
                    <td>
<?php echo $this->form->programa->responsavel_id; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $this->form->submit; ?>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <div id="tabs-1" style="overflow: hidden">
        <form id='frmobjetivos'
              enctype='<?php echo $this->formDescritivo->getEnctype(); ?>'
              action='<?php echo $this->url(array('action' => 'addobjetivo')); ?>?format=json'
              method="post">
                <div style='display: none'>
					<?php echo $this->formDescritivo->id ?>
                	<input type=hidden name="programa_id" class="sync-parent-id" value='<?php if(isset($this->programa->id)) echo $this->programa->id ?>'>
                </div>
                <fieldset>
                    <div style='clear:both'>
						<?php echo $this->formDescritivo->descricao; ?>
                    </div>
					<?php echo $this->formDescritivo->submit; ?>
            </fieldset>
        </form>
        <table width="100%" id="tbobjetivos" class="tb-corpo">
        	<thead class="ui-widget ui-widget-header ">
	            <tr>
	                <th></th>
	                <th>Objetivos</th>
	            </tr>
            </thead>
			<tbody class="ui-widget">            
<?php
                    $cycle = $this->cycle(array('', ''));
                    if(isset($this->programa)):
	                    foreach ($this->programa->findModel_ObjetivosPrograma() as $objetivo) :
	?>
	                        <tr class='lst <?php echo $cycle->next() ?>'>
	                            <td><?php echo $this->lineToolbar('programas', $objetivo) ?></td>
	                            <td><?php echo $objetivo->descricao; ?></td>
	                        </tr>
			<?php   
						endforeach;
					endif;?>
			</tbody>
       </table>
            </div>
    </div>