		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'atividades', 'action'=>'edit'));?>' 
			method="post">
			
			<input type="hidden" id="dependents" value="1,2"/>
			<div style='display:none'>
			
			<?php echo $this->form->getDisplayGroup('ident')?>
			</div>
			<?php echo $this->form->descricao;?><br>
			<?php echo $this->form->responsavel;?><br>
			<?php echo $this->form->intersecao;?><br>
			<?php echo $this->form->valor;?>
			
			<?php echo $this->form->submit;?>
		</form>
		<br></br>
<a href='<?php echo $this->url(array('controller'=>'plano','action'=>'atividade'));?>'>Voltar</a>
<br></br>
<p></p>