<div style="font-size: 1.4em;text-align: justify; text-indent: 4em;width: 90%">
<h3>PAS-E 2011</h3>
<p>A Programação Anual da Saúde Eletrônica 2011 é um sistema de informações
    mantido pela Coordenadoria de Planejamento de Saúde – CPS- da SES SP para o
    acompanhamento da execução do Plano Estadual de Saúde e apoia a elaboração e
    monitoramento da Programação Anual da Saúde e a construção do
    Relatório Anual de Saúde.
</p>
<p>
As telas do sistema são melhor visualizadas nos navegadores Mozilla Firefox® e Google Chrome©.
</p>
<p>Dúvidas e sugestões são bem vindas. Enviar mensagens com cópias para</p>
<div style="margin-left: 4em;width: 100%">
    <br>
cmiranda@saude.sp.gov.br <br>
svallin@saude.sp.gov.br <br>
vchaer@saude.sp.gov.br <br>
</div>



</div>

