
<?php if(!$this->auth): ?>  
<form action="<?php echo $this->url(array('controller'=>'auth', 'action'=>'login'));?>" method="post">  
<label for='username'>Usuário</label>  <input type="text" name="username" />  
<label for='password'>Senha</label><input type="password" name="password" />  
<input type="submit" name="submit" value="Login" />  
</form>  
<?php else:
  $user = Zend_Auth::getInstance()->getIdentity();
?>  
Usuário logado: <?php echo $user->nome;?>.<br />  
<a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'usuarios','action'=>'changepassword'));?> " class="by-ajax">Alterar senha</a>
 | 
<a href="<?php echo $this->url(array('controller'=>'auth','action'=>'logout'));?> ">Sair</a>  
<?php endif; ?>  