<?php 
		$mysession = new Zend_Session_Namespace ( 'mysession' );
		$acl = $mysession->acl;
		$auth = Zend_Auth::getInstance ();
		if ($auth->hasIdentity ()) {
			$role = $auth->getIdentity ()->username;
		} else {
			$role = 'guest';
		}
		$resource = 'programacao:atividades';
		
		if (! $acl->has ( $resource ))
			$resource = null;
		
		$this->res = $resource;
		
		if ($role == 'guest' && ! $acl->hasRole ( 'guest' ))
			$acl->addRole ( 'guest' );

?>



<table class="tb-cabecalho">
    <?php echo $this->partial('instrumentos/cabecalho.phtml',
            array('objeto' => $this->programa, 'nome' => 'Programa', 'acao' => 'Programa', 'detalhar' => ($this->nivel == 'Programa'))); ?>
    <tr>
        <td class="espacador" colspan="2">
            <table class="espacador-table">
                <?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->projeto,
                    'nome' => 'Projeto', 'acao' => 'Projeto', 'detalhar' => ($this->nivel == 'Projeto'))); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 30px">
            <table class="espacador-table">
                <?php
                echo $this->partial('instrumentos/cabecalho.phtml',
                        array('objeto' => $this->objetivo_especifico,
                            'nome' => 'objetivo-especifico', 'detalhar' => ($this->nivel == 'ObjetivoEspecifico'),
                            'label' => 'Objetivo', 'acao' => 'objetivo-especifico',
                            'campo_id' => 'objetivo_especifico_id'));
                ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 45px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->meta,
                    'nome' => 'Meta', 'acao' => 'meta', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 60px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->operacao,
                    'nome' => 'Operacao', 'label' => 'Operação', 'acao' => 'operacao', 'campo_id' => 'operacao_id', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
</table>

<br>

<div class="make-tabs" style="width: 98%; height:100%">
    <ul>
        <li><a href="#tabs-0" >Atividade</a></li>
        <li><a href="#tabs-1" >Histórico</a></li>
        <li><a href="#tabs-2" >Dependências</a></li>
    </ul>

     <div id="tabs-0" style="overflow: hidden">
      <?php // var_dump($this->form->historico); ?>
      
      

	<?php echo $this->Atividades('programacao:atividades',$this->form);?>      
        
    </div>
 
 
 
        <div id="tabs-1" style="overflow: hidden">
            <table border="2" width="50%">
                <tr>
                    <td colspan="2"><b>Histórico</b></td>
                </tr>
                <tr>
                    <td><b>Data</b></td>
                    <td><b>Avaliação/justificativa</b></td>
                </tr>
            <?php
                foreach ($this->atividade_historico as $atividade_historico) {
            ?>
                    <tr>
                        <td>
				<?php echo $atividade_historico->data_prazo(); ?>
                </td>
                <td><?php echo $atividade_historico->avaliacao; ?></td>
                    </tr>
            <?php
                } // foreach
            ?>
            </table>
        </div>

        <div id="tabs-2" style="overflow: hidden">
        	<div style="display: inline-table; margin-bottom: 1em;">
        	
        	
        	
			<?php 
			// *** só é possível adicionar vinculações quando a atividade ainda não foi concluida.
                if(!$this->situacao_atual->data_conclusao) {
			 
					echo "<a href='".$this->url(array('controller'=>'atividades','action'=>'addvinculacao', 'id'=>$this->atividade->id, 'module'=>'programacao'))."'
									title='Novo' 
									class='fg-button ui-state-default fg-button-icon-left ui-corner-all ajax-form-load'>
									<span class='ui-icon ui-icon-plus'>Adicionar Vinculação</span>Adicionar Vinculo</a>";
							
			}?>							        
			</div>
            <table border="2">
                <tr>
                    <td colspan="2"><b>VINCULAÇÕES</b></td>
                </tr>
                <tr>
                    <td><b>Atividade</b></td>
                    <td><b>Observações</b></td>
                    <td><b>&nbsp;</b></td>
                </tr>
            <?php
                foreach ($this->atividadevinculada as $atividadesvinculadas) {
                    $vinculacao = $this->atividades->fetchRow('id=' . $atividadesvinculadas->depende_atividade_id, 'id');
            ?>
                    <tr>
                        <td><a title='<?php echo $atividadesvinculadas->depende_atividade_id . " - " . $vinculacao->descricao; ?>' href='<?php echo $this->url(array('controller' => 'instrumentos', 'action' => 'atividade', 'atividade_id' => $atividadesvinculadas->depende_atividade_id)); ?>'><?php echo $atividadesvinculadas->depende_atividade_id; ?></a></td>
                        <td><?php echo $atividadesvinculadas->justificativa; ?></td>
                        <td>
                    <?php
                    // verificando se usuário pode excluir prazo.
                    $resource = 'deletevinculacao';
                    if (!$acl->has($resource))
                        $resource = null;

                    if ($acl->isAllowed($role, $resource) ||
                            !$resource) {

                        echo "<a href='" . $this->url(array('controller' => 'atividades', 'action' => 'deletevinculacao', 'id' => $atividadesvinculadas->id, 'module' => 'programacao')) . "'
								title='Excluir Vinculação' 
								class='my-button ui-state-default ui-corner-all ajax-form-load'>
								<span class='ui-icon ui-icon-trash'>Excluir Vinculação</span></a>";
                    } // if do acl.
                    ?>
                </td>
            </tr>
            <?php
                }; // foreach
            ?>
        </table>

    </div>

</div>

<script type="text/javascript">
    $(function(){
        atividade = new Atividade();
        atividade.init();
        controleGeral.eventos_classes();
        
   })
    

    function Atividade(){
        this.init = function(){
            this.conclusao();
        };

        this.conclusao = function (){
        	$("#divpercentual").slider({
     		  		 change: function(event, ui) {
	      					id = this.id.substr(3);
	    					$("#"+id).val(ui.value);
         		   			if (parseInt(ui.value) == 100)
         		   			{
             		   			$("#andamento_id").val(6);
             		   			$("#data_conclusao").focus();
         		   			}
             		   			
						 }
     		});
    		$('#andamento_id').change( function() {
        			var valor = parseInt($(this).val());
					if (valor == 6) {
						$("#divpercentual").slider({ value: 100 });
						$("#data_conclusao").focus();
					} else if (valor == 6){
						$("#data_conclusao").focus();
					}
    		});
    		
        };
		
        
    }
</script>
