
<table class="tb-cabecalho">
    <?php echo $this->partial('instrumentos/cabecalho.phtml',
            array('objeto' => $this->programa, 'nome' => 'Programa', 'acao' => 'Programa', 'detalhar' => ($this->nivel == 'Programa'))); ?>
    <tr>
        <td class="espacador" colspan="2">
            <table class="espacador-table">
                <?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->projeto,
                    'nome' => 'Projeto', 'acao' => 'Projeto', 'detalhar' => ($this->nivel == 'Projeto'))); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 30px">
            <table class="espacador-table">
                <?php
                echo $this->partial('instrumentos/cabecalho.phtml',
                        array('objeto' => $this->objetivo_especifico,
                            'nome' => 'objetivo-especifico', 'detalhar' => ($this->nivel == 'ObjetivoEspecifico'),
                            'label' => 'Objetivo Específico', 'acao' => 'objetivo-especifico',
                            'campo_id' => 'objetivo_especifico_id'));
                ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 45px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->meta,
                    'nome' => 'Meta', 'acao' => 'meta', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 60px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->operacao,
                    'nome' => 'Operacao', 'label' => 'Operação', 'acao' => 'operacao', 'campo_id' => 'operacao_id', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
</table>

<br>

<div class="make-tabs" style="width: 98%; height:100%">
    <ul>
        <li><a href="#tabs-0" >Atividade</a></li>
        <li><a href="#tabs-1" >Histórico</a></li>
        <li><a href="#tabs-2" >Dependências</a></li>
    </ul>
    <div id="tabs-0" style="overflow: hidden" >
        <table >
            <tr>
                <td colspan="2">
<?php echo $this->mybar; ?>
                </td>
            </tr>

            <tr >
                <td>
                    <span style="font-weight: bold"> Atividade:</span><br>
                    <?php echo $this->atividade->id . " - " . $this->atividade->descricao ?>
                </td>
            </tr>
            <tr >
                <td>
                    <span style="font-weight: bold">Responsável:</span>
                    <?php echo $this->situacao_atual->findParentModel_Usuarios()->nome ?>
                </td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <td>
                                <span style="font-weight: bold">Data de Início:</span><br>
                                <?php echo $this->situacao_atual->data_inicio() ?>
                            </td>
                            <td>
                                <span style="font-weight: bold">Prazo:</span><br>
                                <?php echo $this->situacao_atual->data_prazo(); ?>
                            </td>
                                <?php if ($this->situacao_atual->data_conclusao) {?>
                                    
                                    <td>
                                        <span style="font-weight: bold">Conclusão:</span><br>
                                        <?php echo $this->situacao_atual->data_conclusao(); ?>
                                    </td>
                                <?php } // if?>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td >
                    <span style="font-size: 1.2em; font-weight: bold;">Situação Atual </span>

                </td>
            </tr>
            <tr>
                <td>
                    
                    <div id="pb-percentual" style="width: 200px;height: 16px">
                        <span style="position:absolute; margin-left:10px; margin-top:2px; text-align: center;width: 200px">
                            <?php echo $this->situacao_atual->percentual; ?>%
                        </span>
                    </div>
                    <?php echo $this->situacao_atual->findParentModel_Andamentos()->descricao; ?>
                </td>
            </tr>
            <tr>
                <td>
                    <span style="font-weight: bold">Descritivo da situação atual</span><br>
                        <?php echo nl2br($this->situacao_atual->avaliacao); ?>
                </td>
                </tr>
            </table>

        </div>

        <div id="tabs-1" style="overflow: hidden">
            <table border="2" width="50%">
                <tr>
                    <td colspan="2"><b>Histórico</b></td>
                </tr>
                <tr>
                    <td><b>Data</b></td>
                    <td><b>Avaliação/justificativa</b></td>
                </tr>
            <?php
                foreach ($this->atividade_historico as $atividade_historico) {
            ?>
                    <tr>
                        <td>
<?php echo $atividade_historico->data_prazo(); ?>
                </td>
                <td><?php echo $atividade_historico->avaliacao; ?></td>
                    </tr>
            <?php
                } // foreach
            ?>
            </table>
        </div>

        <div id="tabs-2" style="overflow: hidden">
            <table border="2">
                <tr>
                    <td colspan="2"><b>VINCULAÇÕES</b></td>
                </tr>
                <tr>
                    <td><b>Atividade</b></td>
                    <td><b>Observações</b></td>
                    <td><b>&nbsp;</b></td>
                </tr>
            <?php
                foreach ($this->atividadevinculada as $atividadesvinculadas) {
                    $vinculacao = $this->atividades->fetchRow('id=' . $atividadesvinculadas->depende_atividade_id, 'id');
            ?>
                    <tr>
                        <td><a title='<?php echo $atividadesvinculadas->depende_atividade_id . " - " . $vinculacao->descricao; ?>' href='<?php echo $this->url(array('controller' => 'instrumentos', 'action' => 'atividade', 'atividade_id' => $atividadesvinculadas->depende_atividade_id)); ?>'><?php echo $atividadesvinculadas->depende_atividade_id; ?></a></td>
                        <td><?php echo $atividadesvinculadas->observacoes; ?></td>
                        <td>
                    <?php
                    // verificando se usuário pode excluir prazo.
                    $resource = 'deletevinculacao';
                    if (!$acl->has($resource))
                        $resource = null;

                    if ($acl->isAllowed($role, $resource) ||
                            !$resource) {

                        echo "<a href='" . $this->url(array('controller' => 'atividades', 'action' => 'deletevinculacao', 'id' => $atividadesvinculadas->id)) . "'
								title='Excluir Vinculação' 
								class='my-button ui-state-default ui-corner-all'>
								<span class='ui-icon ui-icon-trash'>Excluir Vinculação</span></a>";
                    } // if do acl.
                    ?>
                </td>
            </tr>
            <?php
                } // foreach
                // *** só é possível adicionar vinculações quando a atividade ainda não foi concluida.
                if (!$this->situacao_atual->data_conclusao) {
            ?>
                    <tr>
                        <td colspan="2">
                    <?php ?>
                </td>
            </tr>
            <?php
                } // if
            ?>
        </table>

    </div>

</div>
<script type="text/javascript">
    $(function(){
        atividade = new Atividade();
        atividade.init();
    })

    function Atividade(){
        this.init = function(){
            this.percentual();
        }
        this.percentual = function(){
            $("#pb-percentual").progressbar({value: <?php echo $this->situacao_atual->percentual?$this->situacao_atual->percentual:0; ?> })
        }
    }
</script>