
<table class="tb-cabecalho">
    <?php echo $this->partial('instrumentos/cabecalho.phtml',
            array('objeto' => $this->programa, 'nome' => 'Programa', 'acao' => 'Programa', 'detalhar' => ($this->nivel == 'Programa'))); ?>
    <tr>
        <td class="espacador" colspan="2">
            <table class="espacador-table">
                <?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->projeto,
                    'nome' => 'Projeto', 'acao' => 'Projeto', 'detalhar' => ($this->nivel == 'Projeto'))); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 30px">
            <table class="espacador-table">
                <?php
                echo $this->partial('instrumentos/cabecalho.phtml',
                        array('objeto' => $this->objetivo_especifico,
                            'nome' => 'objetivo-especifico', 'detalhar' => ($this->nivel == 'ObjetivoEspecifico'),
                            'label' => 'Objetivo Específico', 'acao' => 'objetivo-especifico',
                            'campo_id' => 'objetivo_especifico_id'));
                ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 45px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->meta,
                    'nome' => 'Meta', 'acao' => 'meta', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
    <tr>
        <td class="espacador" colspan="2" style="padding-left: 60px">
            <table class="espacador-table">
<?php echo $this->partial('instrumentos/cabecalho.phtml', array('objeto' => $this->operacao,
                    'nome' => 'Operacao', 'label' => 'Operação', 'acao' => 'operacao', 'campo_id' => 'operacao_id', 'detalhar' => false)); ?>
            </table>
        </td>
    </tr>
</table>

<br>

<div class="make-tabs" style="width: 98%; height:100%">
    <ul>
        <li><a href="#tabs-0" >Atividade</a></li>
        <li><a href="#tabs-1" >Histórico</a></li>
        <li><a href="#tabs-2" >Dependências</a></li>
    </ul>

     <div id="tabs-0" style="overflow: hidden">
      <?php //echo $this->mybar; ?>

      
        <form id='<?php echo $this->form->getId(); ?>'
              enctype='<?php echo $this->form->getEnctype(); ?>'
              action='<?php echo $this->url(array('action' => 'update', 
				'module' => 'programacao',
				'controller' => 'atividades'));?>?format=json'
              
              method="post">
            <?php echo $this->form->historico->atividade_id;?>
            <?php echo $this->form->historico->responsavel_id;?>
         <!--   ok - a data de início só poderá ser alterada se o andamento não estiver iniciado<br>
            o prazo só poderá ser alterado se o percentual estiver abaixo de 100<br>
            se existirem atividades dependentes, os novos prazos deverão ser pactuados com o responsavel<br>
            quando chegar a 100% exigir data de conclusão e alterar a situação para concluída<br>
            quando alterar a situação para concluida, alterar o percentual para 100% e exigir data de conclusão<br>

            se o percentual estiver em 100 e sofrer alterações, solicitar justificativa e apagar a data de conclusão
             --> 
            <table style="width: 50%; clear: both;" border="2">
            	<tr><td colspan="2">         <span style="font-weight: bold"> Atividade:</span><br>
                    <?php echo $this->atividade->id . " - " . $this->atividade->descricao ?></td></tr>
                <tr>
                	
                    <td>
                        <?php echo $this->form->historico->data_inicio;?>
                    </td>
                    <td>
                        <?php echo $this->form->historico->data_prazo;?>
                    </td>
                </tr>
                <tr>
                	<td colspan="2">                       
                		<?php echo $this->form->historico->percentual;?>
                	</td>

                </tr>
                <tr>
                    <td>
                        <?php echo $this->form->historico->andamento_id;?>
                    </td>
                	<td>
                        <?php echo $this->form->historico->data_conclusao;?>
					</td>                    
                </tr>
                <tr>
                    <td colspan="2">
                        <?php echo $this->form->historico->avaliacao;?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                     <?php
                        echo $this->form->submit;
                        ?>
                    </td>
                </tr>
            </table>
        </form>
        
    </div>
 
 
 
        <div id="tabs-1" style="overflow: hidden">
            <table border="2" width="50%">
                <tr>
                    <td colspan="2"><b>Histórico</b></td>
                </tr>
                <tr>
                    <td><b>Data</b></td>
                    <td><b>Avaliação/justificativa</b></td>
                </tr>
            <?php
                foreach ($this->atividade_historico as $atividade_historico) {
            ?>
                    <tr>
                        <td>
				<?php echo $atividade_historico->data_prazo(); ?>
                </td>
                <td><?php echo $atividade_historico->avaliacao; ?></td>
                    </tr>
            <?php
                } // foreach
            ?>
            </table>
        </div>

        <div id="tabs-2" style="overflow: hidden">
            <table border="2">
                <tr>
                    <td colspan="2"><b>VINCULAÇÕES</b></td>
                </tr>
                <tr>
                    <td><b>Atividade</b></td>
                    <td><b>Observações</b></td>
                    <td><b>&nbsp;</b></td>
                </tr>
            <?php
                foreach ($this->atividadevinculada as $atividadesvinculadas) {
                    $vinculacao = $this->atividades->fetchRow('id=' . $atividadesvinculadas->depende_atividade_id, 'id');
            ?>
                    <tr>
                        <td><a title='<?php echo $atividadesvinculadas->depende_atividade_id . " - " . $vinculacao->descricao; ?>' href='<?php echo $this->url(array('controller' => 'instrumentos', 'action' => 'atividade', 'atividade_id' => $atividadesvinculadas->depende_atividade_id)); ?>'><?php echo $atividadesvinculadas->depende_atividade_id; ?></a></td>
                        <td><?php echo $atividadesvinculadas->observacoes; ?></td>
                        <td>
                    <?php
                    // verificando se usuário pode excluir prazo.
                    $resource = 'deletevinculacao';
                    if (!$acl->has($resource))
                        $resource = null;

                    if ($acl->isAllowed($role, $resource) ||
                            !$resource) {

                        echo "<a href='" . $this->url(array('controller' => 'atividades', 'action' => 'deletevinculacao', 'id' => $atividadesvinculadas->id)) . "'
								title='Excluir Vinculação' 
								class='my-button ui-state-default ui-corner-all'>
								<span class='ui-icon ui-icon-trash'>Excluir Vinculação</span></a>";
                    } // if do acl.
                    ?>
                </td>
            </tr>
            <?php
                } // foreach
                // *** só é possível adicionar vinculações quando a atividade ainda não foi concluida.
                if (!$this->situacao_atual->data_conclusao) {
            ?>
                    <tr>
                        <td colspan="2">
                    <?php ?>
                </td>
            </tr>
            <?php
                } // if
            ?>
        </table>

    </div>

</div>

<script type="text/javascript">
    $(function(){
        atividade = new Atividade();
        atividade.init();
        controleGeral.eventos_classes();
        
   })
    

    function Atividade(){
        this.init = function(){
            this.conclusao();
        };

        this.conclusao = function (){
        	$("#divpercentual").slider({
     		  		 change: function(event, ui) {
	      					id = this.id.substr(3);
	    					$("#"+id).val(ui.value);
         		   			if (parseInt(ui.value) == 100)
         		   			{
             		   			$("#andamento_id").val(6);
             		   			$("#data_conclusao").focus();
         		   			}
             		   			
						 }
     		});
    		$('#andamento_id').change( function() {
        			var valor = parseInt($(this).val());
					if (valor == 6) {
						$("#divpercentual").slider({ value: 100 });
						$("#data_conclusao").focus();
					} else if (valor == 6){
						$("#data_conclusao").focus();
					}
    		});
    		
        };
		
        
    }
</script>
