<?php
$this->campo_id = isset($this->campo_id) ? $this->campo_id : strtolower($this->nome).'_id'; 
$href = $this->url(array('controller'=>'instrumentos',
                        'action'=>strtolower($this->acao) ,
                        $this->campo_id=>$this->objeto->id),null,true);
$this->label = isset($this->label) ? $this->label : $this->nome;
?>
        <tr style="border-bottom: thin solid black"  >
                <td class='text-header' width="60px"><div ><?php echo $this->label?></div></td>
                <td style='padding-left:15px'>
                        <a href='<?php echo $href?>' style="float:left"> <?php echo isset($this->objeto->nome)?$this->objeto->nome:$this->objeto->descricao;?></a>
                </td>
        </tr>
        <?php
         if($this->detalhar): //if-detalhar
                if ((strtolower($this->nome) == "programa")||(strtolower($this->nome) == "projeto")): //programas e projetos ?>
    <?php      endif; // programas e projetos ?>
                <?php
                if (strtolower($this->nome)== "objetivo_especifico"): //if-objetivo-especifico
                        ?>
                        <tr  >
                            <td><div class="subtitulos-descreve-niveis">PARCERIAS:</div></td>
                            <td   style='padding-left:15px'>
                                <?php
                                $select = $this->objeto->select();
                                $select->order('id');
                                $select->where('situacao_id=1');
                                foreach ($this->objeto->findDependentRowset('Model_Parcerias',null,$select) as $parceria):
                                    echo '<li><div class="texto-descreve-niveis">' . $parceria->findParentModel_Parceiros()->nome .'</div></li>';
                                endforeach;?>
                            </td>
                        </tr>
         <?php endif; // objetivo específico
                if(strtolower($this->nome) == "projeto"): //mostra barra
               ?>
                 <tr style="border-bottom: thin solid black" class="ui-state-default">
                     <td colspan="2">
                     <?php echo $this->myToolbar(strtolower($this->nome).'s','top',$this->objeto->id);?>
                     </td>
                 </tr>
 <?php
                endif;//mostra barra
         endif;//if-detalhar?>

