<?php
/**
 * campo usado para cálculo assincrono do progresso
 */
echo '<input type="hidden" id="progresso" name="progresso" value="1">';
echo '<input type="hidden" id="parent_id" name="parent_id" value="">';
?>
<table  width="100%" align="center" cellpadding="0" cellspacing="0" class="tb-corpo" >
    <caption style="font-size: 1.2em" class="ui-widget ui-widget-header">LISTA DE PROGRAMAS</caption>
    <thead class="ui-widget ui-widget-header ">
        <tr class='ui-state-hover'>
            <td class="subtitulos-tabela"> 
                Programas</td>
            <td nowrap="nowrap"  colspan="2" >
                <?php echo $this->myToolbar('programas', 'toptable'); ?>
            </td>
        </tr>
    </thead>
    <tbody class="ui-widget">
<?php
      foreach ($this->programas as $programa) :
?>
            <tr >
                <td >
                    <a href=
                        '<?php echo $this->url(array('action' => 'programa', 'programa_id' => $programa->id)); ?>'>
                        <span class="ui-icon ui-icon-tag" style="float:left"></span>
                        <span class="descricao_item">
                            <?php echo $programa->descricao; ?>
                        </span>
                    </a>
                </td>
                <td align="center" width="50px">
                    <div id="progbar-<?php echo $programa->id;?>" style="height:10px; " class="execucao"></div>
                </td>
                <td style="padding: 0">
                <?php
                    echo $this->myToolbar('programas', 'line', $programa->id);
                ?>
                </td >

            </tr>
        <?php
            endforeach;
        ?>
    </tbody>
</table>
