<?php
/**
 * campo usado para cálculo assincrono do progresso
 */
echo '<input type="hidden" id="progresso" name="progresso" value="'.$this->nivel_id.'">';
echo '<input type="hidden" id="parent_id" name="parent_id" value="'.$this->parent_id.'">';
?>
<table  class="tb-cabecalho">

        <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->programa,
                                                                        'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
        <tr>
            <td class="espacador" colspan="2">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->projeto,
                                                                                    'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 30px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',
                    							array('objeto'=>$this->objetivo_especifico,
                                                       'nome'=>'objetivo-especifico', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'),
                                                       'label'=>'Objetivo Específico', 'acao'=>'objetivo-especifico',
                                                       'campo_id'=>'objetivo_especifico_id' ));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 45px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->meta,
                                                                                                 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
                </table>
            </td>
        </tr>

        <tr style="border-bottom: thin solid black" class="odd">
             <td colspan="2">
             <?php echo $this->myToolbar('metas','top',$this->meta->id);?>
             </td>
        </tr>

</table>
<div style="height: 5px;width: 100%"></div>
<div id="tabela" >

        <table cellpadding="0" cellspacing="0"  class="tb-corpo">
            <caption style="font-size: 1.2em" class="ui-widget ui-widget-header"> OPERAÇÕES</caption>
            <thead class="ui-widget ui-widget-header ">
                <tr class=" ui-state-hover">
                        <td class="subtitulos-tabela">Descrição</td>
                        <td class="subtitulos-tabela" width="50px;"></td>
                        <td width="4px"><?php echo $this->myToolbar('operacoes','toptable');?></td>
                </tr>
            </thead>
            <tbody class="ui-widget">
                <?php
                $cycle=$this->cycle(array('',''));
                foreach ($this->operacoes as $operacao){?>
                <tr class="<?php echo $cycle->next()?>">
                        <td>
                            <div >
                                <a href='<?php echo $this->url ( array ('action' => 'operacao', 'operacao_id' => $operacao->id ) );?>'>
                                    <span class="ui-icon ui-icon-play" style="float:left"></span>
                                    <span class="descricao_item"><?php echo $operacao->descricao;?></span>
                                </a>
                            </div>
                        </td>
                        <td>
                            <div id="progbar-<?php echo $operacao->id;?>" style="height:10px; " class="execucao"></div>
                        </td>
                        <td class="texto">
                            <?php echo $this->myToolbar ( 'operacoes' , 'line', $operacao->id  );?>
                        </td>
                </tr>
                <?php
                }?>
            </tbody>
        </table>

</div>

