<?php
/**
 * campo usado para cálculo assincrono do progresso
 */
echo '<input type="hidden" id="progresso" name="progresso" value="'.$this->nivel_id.'">';
echo '<input type="hidden" id="parent_id" name="parent_id" value="'.$this->parent_id.'">';
?>
<table  class="tb-cabecalho">

        <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->programa,
                                                                        'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
        <tr>
            <td class="espacador" colspan="2">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->projeto,
                                                                                    'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 30px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',
                    							array('objeto'=>$this->objetivo_especifico,
                                                       'nome'=>'objetivo-especifico', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'),
                                                       'label'=>'Objetivo', 'acao'=>'objetivo-especifico',
                                                       'campo_id'=>'objetivo_especifico_id' ));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 45px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->meta,
                                                                                                 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
                </table>
            </td>
        </tr>

        <tr style="border-bottom: thin solid black" class="odd">
             <td colspan="2">
             <?php echo $this->myToolbar('programacao:metas','top',$this->meta->id);?>
             </td>
        </tr>

</table>
<div style="height: 5px;width: 100%"></div>

<div class="make-tabs">
    <ul>
        <li><a href="#tabs-0">Lista</a></li>
        <li><a href="#tabs-1">Gantt</a></li>
        <li><a href="#tabs-2">Indicadores</a></li>
    </ul>
    
    <div id="tabs-0" style="overflow: hidden">
        <div id="tabela" >

            <table cellpadding="0" cellspacing="0"  class="tb-corpo">
                <caption style="font-size: 1.2em" class="ui-widget ui-widget-header"> OPERAÇÕES</caption>
                <thead class="ui-widget ui-widget-header ">
                    <tr class=" ui-state-hover">
                            <td class="subtitulos-tabela">Descrição</td>
                            <td class="subtitulos-tabela" width="50px;"></td>
                            <td width="4px"><?php echo $this->myToolbar('programacao:operacoes','toptable');?></td>
                    </tr>
                </thead>
                <tbody class="ui-widget">
                    <?php
                    foreach ($this->operacoes as $operacao){?>
                    <tr >
                            <td>
                                <div >
                                    <a href='<?php echo $this->url ( array ('action' => 'operacao', 'operacao_id' => $operacao->id ) );?>'>
                                        <span class="ui-icon ui-icon-play" style="float:left"></span>
                                        <span class="descricao_item"><?php echo $operacao->descricao;?></span>
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div id="progbar-<?php echo $operacao->id;?>" style="height:10px; " class="execucao"></div>
                            </td>
                            <td class="texto">
                                <?php echo $this->myToolbar ( 'programacao:operacoes' , 'line', $operacao->id  );?>
                            </td>
                    </tr>
                    <?php
                    }?>
                </tbody>
            </table>
        </div>
    </div>
    <div id="tabs-1" style="overflow: hidden">
        <div style="position:relative" class="gantt" id="GanttChartDIV"></div>
    </div>
    <div id="tabs-2" style="overflow: hidden">
        

        
            <table cellpadding="0" cellspacing="0"  class="tb-corpo">
                <caption style="font-size: 1.2em" class="ui-widget ui-widget-header"> Indicadores</caption>
                <thead class="ui-widget ui-widget-header ">
                    <tr class=" ui-state-hover">
                            <td class="subtitulos-tabela">Descrição</td>
                            <td style="width:6em">
                                <div class="fg-toolbar ui-widget ui-widget-header ui-corner-all ui-helper-clearfix" style="padding-right: 0.1em">
                                <div class="fg-buttonset ui-helper-clearfix" style="padding-right: 0em; width:100%">
                                    <a href='<?php echo $this->url(array('controller'=>'indicadores','action'=>'create','module'=>'programacao','meta_id'=>$this->meta->id ),null,true)?>'
                                        title='Novo Indicador' 
                                        class='fg-button ui-state-default fg-button-icon-left ui-corner-all ajax-form-load'>
                                        <span class='ui-icon ui-icon-plus'>Novo Indicador</span>Novo Indicador</a>
                                </div>
                                </div>
                            </td>
                    </tr>
                </thead>
                <tbody class="ui-widget">
            <?php
            $indicadores = $this->meta->findModel_IndicadoresMeta();
            foreach ($indicadores as $indicadormeta) {
                $indicador = $indicadormeta->findParentModel_Indicadores();
                ?>
                    <tr >
                            <td>
                                <div >
                                    <a href='<?php echo $this->url ( array ('action' => 'show', 'controller' => 'indicadores', 'module'=>'default' ) );?>'>
                                        <span class="ui-icon ui-icon-play" style="float:left"></span>
                                        <span class="xdescricao_item"><?php echo $indicador->descricao;?></span>
                                    </a>
                                </div>
                            </td>
                            <td class="texto">
                                <?php echo $this->indicadoresToolbar($indicador) ?>
                            </td>
                    </tr>
            <?php
            }
            ?>
                </tbody>
            </table>
        </div>

</div>

<script type="text/javascript" >

  // here's all the html code neccessary to display the chart object

  // Future idea would be to allow XML file name to be passed in and chart tasks built from file.

     g = new JSGantt.GanttChart('g',document.getElementById('GanttChartDIV'), 'month');
        g.setShowRes(0); // Show/Hide Responsible (0/1)
        // define a quantidade de caracteres que aparecerão na descrição
        g.setMaxLengthDescription(50)
        g.setShowDur(1); // Show/Hide Duration (0/1)
        g.setShowComp(1); // Show/Hide % Complete(0/1)

        g.setDateInputFormat("dd/mm/yyyy");
        g.setFormatArr("day","week","month");
        g.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

        g.setShowStartDate(0); // Show/Hide Start Date(0/1)
        g.setShowEndDate(0); // Show/Hide End Date(0/1)
        g.setDateDisplayFormat('dd/mm/yyyy') // Set format to display dates ('mm/dd/yyyy', 'dd/mm/yyyy', 'yyyy-mm-dd')

      //var gr = new Graphics();

      if( g ) {
                JSGantt.parseXML('<?php echo $this->url(array('action'=>'gantt'));?>?format=xml',g)
                g.Draw();
                g.DrawDependencies();
      }else{
        alert("not defined");
      }

</script>