<?php
/**
 * campo usado para cálculo assincrono do progresso
 */
echo '<input type="hidden" id="progresso" name="progresso" value="'.$this->nivel_id.'">';
echo '<input type="hidden" id="parent_id" name="parent_id" value="'.$this->parent_id.'">';
?>
<table  class="tb-cabecalho">

        <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->programa,
                                                                        'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
        <tr>
            <td class="espacador" colspan="2">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->projeto,
                                                                                    'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 30px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',
                    							array('objeto'=>$this->objetivo_especifico,
                                                       'nome'=>'objetivo-especifico', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'),
                                                       'label'=>'Objetivo', 'acao'=>'objetivo-especifico',
                                                       'campo_id'=>'objetivo_especifico_id' ));?>
                </table>
            </td>
        </tr>
        <tr>
            <td class="espacador" colspan="2" style="padding-left: 45px">
                <table class="espacador-table">
                    <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->meta,
                                                                                                 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
                </table>
            </td>
        </tr>
		<tr>
            <td class="espacador" colspan="2" style="padding-left: 60px">
                <table class="espacador-table">
					<?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->operacao,
													 'nome'=>'Operacao', 'label'=>'Operação', 'acao'=>'operacao', 'campo_id'=>'operacao_id', 'detalhar'=>false));?>
	                </table>
            </td>
        </tr>
</table>	

	
		<table cellpadding="0" cellspacing="0" class="tb-corpo">
                    <caption style="font-size: 1.2em" class="ui-widget ui-widget-header"> ATIVIDADES</caption>
                    <thead class="ui-widget ui-widget-header ">
                    <tr class=" ui-state-hover">
                            <td class="subtitulos-tabela" width="55%">Descrição</td>
                            <td  class="subtitulos-tabela" width="70px;">Data Início</td>
                            <td  class="subtitulos-tabela" width="100px;">Prazo</td>
                            <td  class="subtitulos-tabela" width="100px;">Andamento</td>
                            <td  class="subtitulos-tabela" width="70px;">Peso</td>
                            <td class="subtitulos-tabela" width="50px;"></td>
                            <td width="4px"><?php echo $this->myToolbar('programacao:atividades','toptable');?></td>
                    </tr>
                    </thead>
			<tbody class="ui-widget ">
				<?php
				$cycle=$this->cycle(array('','')); 
				foreach ($this->atividades as $atividade){?>
				<tr class="<?php echo $cycle->next()?>">
					<td>
					<div >
						<a href=
							'<?php echo $this->url ( array ('controller' => 'instrumentos', 'action' => 'atividade', 'atividade_id' => $atividade->id ));?>'>
							<span class="ui-icon ui-icon-play" style="float:left"></span>
                                                         <span class="descricao_item"><?php echo $atividade->descricao;?></span>
						</a>
					</div>
					</td>
					<td >
						<?php 
						$this->select_historico->reset('where');
						$this->select_historico->where('situacao_id=1');
						$historicos =$atividade->findModel_AtividadesHistorico($this->select_historico);
						$historico = $historicos->current();
						echo $historico->data_inicio();
						?>				
					</td>
					<td >
						<?php echo $historico->data_prazo();?>				
					</td>
					<td >
						<?php echo $historico->findParentModel_Andamentos()->descricao;?>				
					</td>
					<td nowrap="nowrap">
						<?php echo $this->mudaPeso('programacao:atividades' , $atividade->id, $atividade->peso );?>						
					</td>
					<td>
						<div id="progbar-<?php echo $atividade->id;?>" style="height:10px; " class="execucao"></div>
					</td>
					<td >
						<?php echo $this->myToolbar ( 'programacao:atividades' , 'line', $atividade->id  );?>
					</td>
				</tr>
				<?php 
				}?>
			</tbody>
		</table>
		<div id="mensagem-peso"></div>

		
	<script>
	$(function() {
		$( ".slider-peso" ).slider({ animate: true , step: 5});
		$(".slider-peso").each(function(){
			var input = $(this).nextAll('input');
			var peso =  input.val();
			var atividade_id = input.attr("id");
			$(this).slider({value: peso,
							    change: function( event, ui ) {
								gravaPeso(ui.value, atividade_id)
								verificaPesos();
								},
							slide: function( event, ui ) {
									$("#"+atividade_id).val(ui.value);
								}
			});
			verificaPesos();
										
		});

	});

	function verificaPesos(){
		var soma = parseInt(0);
		$(".slider-peso").each(function(){
			var input = $(this).nextAll('input');
			var peso =  input.val();		
			soma = soma + parseInt(peso);
			$mensagem = (parseInt(soma) > parseInt(100))?"A soma dos pesos é maior do que 100":"";
			$("#mensagem-peso").html($mensagem);
		});

	}
	function gravaPeso(peso, id){

        $.ajax({
            type: "POST",
            url: "<?php echo $this->url(array('action' => 'mudapeso', 
				'module' => 'programacao',
				'controller' => 'atividades')); ?>?format=json",
			      data: ({id   : id,
			      	      peso : peso}),
            success: function(data, status,xhr){
                //Mensageiro.onSuccess(data);
            } ,
            complete:function(XMLHttpRequest, textStatus){
                if(textStatus=='success'){
                   // Mensageiro.onComplete(XMLHttpRequest)
                }
            },
            error: function(XMLHttpRequest, textStatus, errorThrown){
                Mensageiro.onError(XMLHttpRequest,textStatus,errorThrown);
            }

        });
        return false;

	}
	
	</script>

		
		