<?php
/**
 * campo usado para cálculo assincrono do progresso
 */
echo '<input type="hidden" id="progresso" name="progresso" value="'.$this->nivel_id.'">';
echo '<input type="hidden" id="parent_id" name="parent_id" value="'.$this->parent_id.'">';
?>
<table cellpadding="0" cellspacing="0" class="tb-cabecalho">
        <?php echo $this->partial('instrumentos/cabecalho.phtml',array('objeto'=>$this->programa,
                                 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>

</table>
<div style="height: 5px;width: 100%"></div>
<div>
    <table cellpadding="0" cellspacing="0" class="tb-corpo">
        <caption style="font-size: 1.2em" class="ui-widget ui-widget-header">PROJETOS</caption>
            <thead class="ui-widget ui-widget-header ">
                <tr class=" ui-state-hover">
                    <th  class="subtitulos-tabela"></th>
                    <th  class="subtitulos-tabela" width="50px"></th>
                    <th><?php echo $this->myToolbar('programacao:projetos','toptable');?></th>
                </tr>
            </thead>

            <tbody class="ui-widget ">
                <?php
                foreach ($this->projetos as $projeto):?>
                <tr >
                    <td>
                        <div>
                            <a href='<?php echo $this->url ( array ('action' => 'projeto', 'projeto_id' => $projeto->id ) );?>'>
                                <span class="ui-icon ui-icon-play" style="float:left"></span>
                                <span class="descricao_item"><?php echo $projeto->nome;?></span>
                            </a>
                        </div>
                    </td>
                    <td align="center">
                        <div id="progbar-<?php echo $projeto->id;?>" style="height:10px; " class="execucao"></div>
                    </td>
                    <td class="texto"  width="4%">
                            <?php echo $this->myToolbar ( 'programacao:projetos' , 'line', $projeto->id  );?>
                    </td>
                <?php endforeach;?>
            </tbody>
    </table>

</div>

