<h3>Confirmar exclusão</h3>

<h3>Deseja remover o vínculo entre : <br> 
<span style="color: red;"><?php echo $this->atividadePai->id ."-" .$this->atividadePai->descricao;?></span> e
<span style="color: red;"><?php echo $this->atividadeFilho->id ."-" .$this->atividadeFilho->descricao;?></span></h3>

<form id='<?php echo $this->form->getId();?>'
              enctype='<?php echo $this->form->getEnctype();?>'
              action='<?php echo $this->url(array('action' => 'deletevinculacao'));?>?format=json'
              method="post">
<?php echo $this->form->id;?>
    <table>
        <tr>
            <td><?php echo $this->form->submit; ?></td>
            <td><?php echo $this->form->dialog_close; ?></td>
        </tr>
    </table>
</form>
