<script type="text/javascript">
<!--
$(
		function()
		{
			$(".submit_descritivo").click(function(e)
			{
				e.preventDefault()
			    var options = {
			        success:       showDescritivo,
			        dataType:	'json'
			    }; 
			    // bind form using 'ajaxForm'
			    formulario  = $(this).parents('form');
			    $(formulario).ajaxSubmit(options)				
			});
		}
)
function showDescritivo(data,result,obj){
	if(data.descricao != undefined){
		tabela = obj.attr('id');
		tabela = tabela.substr(3);
		$("#tb"+tabela).append("<tr><td>"+data.descricao+"</td></tr>")
		obj[0].descricao.value="";
		
	}
}

//-->
</script>
<div id="formtabs" style="width: 800px; height:100%">
	<ul>
		<li><a href="#tabs-0" >Ação</a></li>
		<li><a href="#tabs-1">Objetivos</a></li>
		<li><a href="#tabs-2">Estratégias</a></li>
		<li><a href="#tabs-3">Metas</a></li>
	</ul>
	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'acoes', 'action'=>'save'));?>' 
			method="post">
			<input type="hidden" id="dependents" value="1,2,3"/>
			<div style='display:none'>
			<?php echo $this->form->getDisplayGroup('ident') ?>
			</div>
			<?php echo $this->form->descricao;?>
			
			<?php echo $this->form->recursos;?>
			
			<?php echo $this->form->cronograma;?>
			
			<?php echo $this->form->submit;?>
		</form>

	</div>

	<div id="tabs-1" style="overflow: hidden">
		<?php if(isset($this->acao)){ ?>
		<form id='frmobjetivos' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'acoes', 'action'=>'addobjetivo'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='acao_id' value='<?php echo $this->acao->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<table width="100%" id="tbobjetivos" class='ui-widget ui-widget-panel'>
			<tr>
				<th>Objetivos</th>
			</tr>
	<?php  
			foreach($this->acao->findModel_ObjetivosAcao() as $objetivo){
	?>
			<tr>
				<td><?php echo $objetivo->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
		<button>Proximo >></button>
	</div>
	<div id="tabs-2" style="overflow: hidden">

		<?php if(isset($this->acao)){ ?>
		<form id='frmestrategias' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'acoes', 'action'=>'addestrategia'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='acao_id' value='<?php echo $this->acao->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<br>
		<table width="100%" id="tbestrategias" class='ui-widget ui-widget-panel'>
			<tr>
				<th>Estratégias</th>
			</tr>
	<?php  
			foreach($this->acao->findModel_EstrategiasAcao() as $estrategia){
	?>
			<tr>
				<td><?php echo $estrategia->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
		<button>Proximo >></button>

		
	</div>
	<div id="tabs-3" style="overflow: hidden">
		
		<?php if(isset($this->acao)){ ?>
		<form id='frmmetas' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'acoes', 'action'=>'addmeta'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='acao_id' value='<?php echo $this->acao->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<br>
		<table width="100%" id="tbmetas" class='ui-widget ui-widget-panel'>
			<tr>
				<th>Metas</th>
			</tr>
	<?php  
			foreach($this->acao->findModel_MetasAcao() as $meta){
	?>
			<tr>
				<td><?php echo $meta->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
	</div>
	
</div>