<div class="make-tabs" style="height:100%">
	<ul>
		<li><a href="#tabs-0" >Relatórios</a></li>
	</ul>

	<div id="tabs-0" style="overflow: hidden">
<div id="tabela" class='inner' border="0">
<br></br>
	<table width="100%">
		<tbody>
		<tr><td>
		<?php 
		$mysession = new Zend_Session_Namespace ( 'mysession' );
		$acl = $mysession->acl;
				
		$auth = Zend_Auth::getInstance();
		if ($auth->hasIdentity ()) {
			$role = $auth->getIdentity ()->username;
		} else {
			$role = 'guest';
		}
				
		$resource = $this->resource;
		if (! $acl->has ( $resource )) 
			$resource = null;
				
		if($acl->isAllowed($role,$resource) ||
				!$resource){ 
			?>
			<!-- <a href='<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'editgestao' ) );?>'>
			Atualizar Relatório de Gestão
			</a>
			 -->
		<?php 
		} else {
		?>
			<!-- Atualizar Relatório de Gestão (você precisa logar para acessar este relatório) -->
		<?php 
		} // if $acl
		?>
		</td></tr>
			<tr>
				<td>
				<a href='<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatoriogestao' ) );?>'>
				Relatório de Gestão
				</a>
				</td>
			</tr>
			<tr>
				<td>
					<a href='<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatorioplano' ) );?>'>
					Relatório do Plano
					</a>
				</td>
			</tr>
			<tr>
				<td>
					<a href='<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatorioatividaderesponsavel' ) );?>'>
					Relatório de Atividades com Responsável
					</a>
				</td>
			</tr>
			<tr>
				<td>
					<h3>Relatório trimestral</h3>
					<table>
						<tr>
							<td>Primeiro trimestre</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'checklist', 'trimestre'=>'1' ) );?>'>
								Checklist
								</a>
							</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'trimestral', 'trimestre'=>'1' ) );?>'>
								Emitir
								</a>
							</td>
						</tr>
						<tr>
							<td>Segundo trimestre</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'checklist', 'trimestre'=>'2' ) );?>'>
								Checklist
								</a>
							</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'trimestral', 'trimestre'=>'2' ) );?>'>
								Emitir
								</a>
							</td>
						</tr>
						<tr>
							<td>Terceiro trimestre</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'checklist', 'trimestre'=>'3' ) );?>'>
								Checklist
								</a>
							</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'trimestral', 'trimestre'=>'3' ) );?>'>
								Emitir
								</a>
							</td>
						</tr>
						<tr>
							<td>Quarto trimestre</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'checklist', 'trimestre'=>'4' ) );?>'>
								Checklist
								</a>
							</td>
							<td>
								<a href='<?php echo $this->url ( array ('controller' => 'reports', 'action' => 'trimestral', 'trimestre'=>'4' ) );?>'>
								Emitir
								</a>
							</td>
						</tr>

					</table>
				</td>
			</tr>
		</tbody>
	</table>
<br></br>
</div>
</div>
</div>