<?php 
if ($this->imprimir == "sim"){
	?>
	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	</head>
	<?php 
}
?>
<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>'
			action='' 
			method="post">
<?php 
if ($this->imprimir == "não")
{
	?>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatorioatividaderesponsavelprint' ) ); ?>"><img src="<?php echo $this->baseUrl (); ?>/images/print_icon.jpg" border="0" /></a>
	<?php 
}
?>			
<table width="90%" border="1" align="center">
	<?php 
	foreach($this->programa->fetchAll("situacao_id=1", "id") as $programas){
	?>
		<tr>
			<td  colspan="4">
			<br>
			<table border="0" width="100%">
				<tr bgcolor="0099FF">
					<td>
					<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000"><b>PROGRAMA <?php echo $programas->id; ?></b></font>
					</td>
					<td>
					<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000"><b>Reponsável</b></font>
					</td>
				</tr>
				<tr bgcolor="66FF99">
					<td>
					<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
					<b><?php echo $programas->descricao; ?></b>
					</font>
					</td>
					<td>
					<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
					<?php 
					$nome = "";
					foreach ($this->responsavel->fetchAll("id=" . $programas->responsavel_id) as $responsaveis)
					{
						$nome = $responsaveis->nome;
					}
					?>
					<b><?php echo $nome; ?></b>
					</font>
					</td>
				</tr>
				<tr>
			    	<td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			    </tr>
			</table>
			</td>
		</tr>
		<?php 
		foreach($this->projeto->fetchAll("programa_id=".$programas->id." and projeto_id is null and situacao_id=1", "id") as $projetos){
		?>
			<tr>
				<td  colspan="4">
				<table border="0" width="100%">
					<tr bgcolor="66FF99">
						<td>
						<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
						<b>PROJETO: <?php echo $projetos->descricao; ?></b>
						</font>
						</td>
						<td>
						<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
						<?php 
						$nome = "";
						foreach ($this->responsavel->fetchAll("id=" . $projetos->responsavel_id) as $responsaveis)
						{
							$nome = $responsaveis->nome;
						}
						?>
						<b><?php echo $nome; ?></b>
						</font>
						</td>
					</tr>
					<tr>
				    	<td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
				    </tr>
				</table>		
				</td>
			</tr>
			<?php 
			foreach($this->subprojeto->fetchAll("programa_id=" . $programas->id." and situacao_id=1", "id") as $subprojetos){
			?>
				<?php 
				if (($subprojetos->projeto_id != "") && ($subprojetos->projeto_id == $projetos->id)){
				?>
					<tr>
						<td  colspan="4">
						<table border="0" width="100%">
							<tr  bgcolor="66FF99"><td>
								<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
								<b>SUBPROJETO: <?php echo $subprojetos->descricao; ?></b>
								</font>
								</td>
								<td>
								<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
								<?php 
								$nome = "";
								foreach ($this->responsavel->fetchAll("id=" . $subprojetos->responsavel_id) as $responsaveis)
								{
									$nome = $responsaveis->nome;
								}
								?>
								<b><?php echo $nome; ?></b>
								</font>
								</td>
							</tr>
							<tr>
						    	<td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
						    </tr>
						</table>		
						</td>
					</tr>
				<?php 
				} // if do cabeçalho para subprojeto
				?>
				<?php 
				if (($projetos->id == $subprojetos->id) || ($subprojetos->projeto_id == $projetos->id)){
					$projeto_id = $subprojetos->id;
					foreach($this->objetivoespecifico->fetchAll("projeto_id=" . $projeto_id." and situacao_id=1") as $objetivosespecificos){
					?>
						<tr>
							<td  colspan="4">
							<table border="0" width="100%">
								<tr  bgcolor="66FF99">
									<td colspan="2">
									<font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="000000">
									<b>OBJETIVO ESPECÍFICO: <?php echo $objetivosespecificos->descricao; ?></b>
									</font>
									</td>
								</tr>
								<tr>
							    	<td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
							    </tr>
							</table>
							</td>
						</tr>									
						<tr>
							<td>

				            <table width="100%" border="1">
					            <tr bgcolor="0099FF">
						            <td>
						            <font face="Arial, Helvetica, sans-serif" size="2" color="000000">
						            <b>Meta</b>
						            </font>
						            </td>
						            <td>
						            <font face="Arial, Helvetica, sans-serif" size="2" color="000000">
						            <b>Operação</b>
						            </font>
						            </td>
						            <td>
						            <font face="Arial, Helvetica, sans-serif" size="2" color="000000">
						            <b>Atividade</b>
						            </font>
						            </td>
						            <td>
						            <font face="Arial, Helvetica, sans-serif" size="2" color="000000">
						            <b>Responsável</b>
						            </font>
						            </td>
						            <td>
						            <font face="Arial, Helvetica, sans-serif" size="2" color="000000">
						            <b>Interseção</b>
						            </font>
						            </td>
					            </tr>
								<?php 
								$sc = "poa2010"; // schema
								$meta_id = 0;
								$operacao_id = 0;
								$select = $this->atividade->select()
												->setIntegrityCheck(false)
												->from(array("m" => "$sc.metas"), array("descricao_meta" => "descricao", "meta_id" => "id"));
								$select->joinleft(array("o" => "$sc.operacoes"),
												"o.meta_id = m.id and o.situacao_id = 1", array("descricao_operacao" => "descricao", "operacao_id" => "id"));
								$select->joinleft(array("a" => "$sc.atividades"),
												"a.operacao_id = o.id and a.situacao_id = 1", array("descricao_atividade" => "descricao", "atividade_id" => "id", "valor", "responsavel", "intersecao", "prazo_data", "conclusao_data"));
								$select->where("m.situacao_id = 1 and m.objetivo_especifico_id = " . $objetivosespecificos->id); 												
								$select->order(array("m.id", "o.id", "a.id"));
								foreach($this->atividade->fetchAll($select) as $registros){
									?>
									<tr>
									<?php 
									if ($registros->meta_id != $meta_id){
										?>
					                    <td style="border-bottom-width:0">
					                    <font face="Arial" size="1" color="000000">
					                    <?php echo $registros->descricao_meta; ?>
					                    </font>
					                    </td>
										<?php 
										$meta_id = $registros->meta_id;
									} else {
										?>	
					    				<td style="border-bottom-width:0; border-top-width:0">&nbsp;</td>            
										<?php
									} // if
									if ($registros->operacao_id != $operacao_id){
										?>
										<td style="border-bottom-width:0">
										<font face="Arial" size="1" color="000000">
										<?php echo $registros->descricao_operacao; ?>
										</font>
										</td>
										<?php
										$operacao_id = $registros->operacao_id;				
									} else {
										?>	
					    				<td style="border-bottom-width:0; border-top-width:0">&nbsp;</td>            
										<?php
									}
									?>
									<td>
					                <font face="Arial" size="1" color="000000">
					                <?php echo $registros->atividade_id . " - " . $registros->descricao_atividade; ?>
					                </font>
					                </td>
					                <td align="center">
					                <font face="Arial" size="1" color="000000">
					                <?php echo $registros->responsavel; ?>
					                </font>
					                </td>
					                <td align="center">
					                <font face="Arial" size="1" color="000000">
					                <?php echo $registros->intersecao; ?>
					                </font>
					                </td>
									</tr>
									
									<?php 
								} // foreach
								?>
							</table>
							</td>
						</tr>
					<?php 
					} // foreach objetivos especificos
				} // if de projetos e subprojetos
			} // select subprojetos
		} // select projetos
	} // select programas
	?>
</table>
</form>
<?php 
if ($this->imprimir == "sim")
{
	?>
	<script language="JavaScript">
	window.print();
	</script>
	<?php 
}
?>