<h3>Alterar Ajuda</h3>
<div class="make-tabs" style="height:100%">
	<ul>
		<li><a href="#tabs-0" >Ajuda</a></li>
	</ul>

	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'ajudas', 'action'=>'save'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->form->id ?>
			<?php echo $this->form->pagina; ?>
			<?php echo $this->form->acao; ?>
			</div>

			<table width="100%" border="0">
			<tr><td>
			<?php echo $this->form->textoajuda; ?>
			<?php echo $this->setupEditor( 'textoajuda' ); ?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->submit;?>
			</td></tr>
			</table>
		</form>
	</div>
</div>
<br/>
<div style="clear:both;">
<a href='<?php echo $this->url(array('controller'=>'plano', 'action'=>'operacao'))?>'>Voltar</a>
</div>
