

<h3>Indicador: <?php echo $this->indicador->descricao;?></h3>
<div style="border: thin solid black;overflow:auto; padding:10px;">
		<form enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'indicadores', 'action'=>'configurar'));?>' 
			method="post">
			
			
			<div style='display:none'>
			
			<?php echo $this->form->id;?>
			<?php echo $this->form->indicador_id;?>
			</div>
			<?php echo $this->form->tipo_periodo_id;?>
			
			<br></br>
			
			<?php echo $this->form->base;?>
            
            <br>
            <fieldset style='clear: both;'>
            <legend>Campos para preenchimento</legend>
            Ex: se o indicador é "Número de casos de determinado agravo" então será preenchido apenas o resultado<br>
                se é "Percentual de ocorrencia de determinado agravo" onde se conhece o  númerador e denominador se deseja que o sistema efetue o cálculo, então deverá ser marcado "Numerador" e "Denominador"<br>
                se é "Percentual de ocorrencia de determinado agravo" onde se conhece o  apenas o resultado,  então deverá ser marcado "Resultado"
                <br></br>
            <?php echo $this->form->campos;?>
			</fieldset>
            <br>
            <fieldset style='clear: both;'>
                <legend>Data inicial de preenchimento do indicador</legend>
            <?php echo $this->form->mes;?> / <?php echo $this->form->ano;?> 
            </fieldset>
            <br></br>
			<?php echo $this->form->submit;?>
            
			<br/>
		</form>
</div>
<br/>
<a href='<?php echo $this->baseUrl().$this->urlback; ?>'> Voltar</a>
<br/>
<table id='tbconfiguracoes'>
	<tr>
		<td></td>
		<td>Tipo</td>
		<td>Base</td>
	</tr>
	<?php foreach($this->indicador->findDependentRowset('Model_IndicadoresConfiguracoes') as $ic){?>
		<tr>
			<td>
			<a href='<?php echo $this->url(array('controller'=>'changestatus','action'=>'delete', 'model'=>'Model_IndicadoresConfiguracoes', 'id'=>$ic->id))?>'
					class='my-button ui-state-default ui-corner-all deletedescription'
					title='Excluir' 
					id='delete-configuracoes-<?php echo $ic->id?>'
					>
					<span class='ui-icon ui-icon-trash '></span>
				</a>
			</td>
			<td>
				<?php echo $ic->findParentRow('Model_TiposPeriodos')->descricao;?>
			</td>
			<td>
				<?php echo $ic->base;?>
			</td>
			
		</tr>
	<?php }?>
</table>
<script>
if($("#base").val()==1){
	$("#campos-nd").attr('disabled','disabled');
	$("#campos-r").attr('checked','checked')
}
	
$("#base").live('change',function(e)
		{
			obj = $(this)
			if(obj.val()==1){
				$("#campos-r").attr('checked','checked')
				$("#campos-nd").attr('disabled','disabled')
			}else{
				$("#campos-nd").removeAttr('disabled')
			}
			
		});	
</script>