

<h3>Indicador: <?php echo $this->indicador->descricao;?></h3>
<div style="border: thin solid black;overflow:auto; padding:10px;">
		<form enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'indicadores', 'action'=>'configurarqualitativos'));?>' 
			method="post">
			
			
			<div style='display:none'>
			
			<?php echo $this->form->id;?>
			<?php echo $this->form->indicador_id;?>
			</div>
			
			<?php echo $this->form->descricao;?>
            
            <br></br>
			<?php echo $this->form->submit;?>
            
			<br/>
		</form>
</div>
<br/>
<a href='<?php echo $this->baseUrl(). $this->urlback; ?>'> Voltar</a>
<br/>
<table  id='tbcategorias'>
	<tr>
		<td></td>
		<td>Categorias</td>
	</tr>
	<?php foreach($this->indicador->findDependentRowset('Model_OpcoesQualitativos') as $ic){?>
		<tr>
			<td>
			<a href='<?php echo $this->url(array('controller'=>'changestatus','action'=>'delete', 'model'=>'Model_OpcoesQualitativos', 'id'=>$ic->id))?>'
					class='my-button ui-state-default ui-corner-all deletedescription'
					title='Excluir'
					id='delete-categorias-<?php echo $ic->id?>'
					>
					<span class='ui-icon ui-icon-trash '></span>
				</a>
			</td>
			<td>
				<?php echo $ic->descricao;?>
			</td>
			
		</tr>
	<?php }?>
</table>