
<div id="liste">
	<div class='forgrid'>
	    <table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
	    <div id="pager" class="scroll" style="text-align:center;"></div>
    </div>    

</div>
 
<script type="text/javascript"><!--
var lastsel; 
    $(document).ready(function(){
    	$('.forgrid').each(function (){
			gr = $('table',this)[0]
			pg = $('div',this)[0]
			enableGrid(gr,pg)
		})

    });
	function enableGrid(obj,pg)
	{
        $(obj).jqGrid({
            width: 900,
            height: 240,
            rownumbers: true,
            url:'<?php echo $this->baseUrl() ?>/indicadores/localizar/indicador_configuracao_id/<?php echo $this->indicador_configuracao_id;?>',
            datatype: 'json',
            mtype: 'POST',
            
			colNames:['id', 'Competencia (AAAAMM)' <?php echo $this->colnames; ?>], 
			colModel:[   {name:'id',index:'id', width:2},
			             {name:'competencia',index:'competencia asc', width:100,editable:true, edittype:"text", editrules:{number:true}}
                         <?php echo $this->colmodels;?> 
			            ], 
			            pager: '#pager',
			            rowNum:30,
			            rowList:[10,20,30],
			            sortname: 'competencia',
			            sortorder: "asc",
			            viewrecords: true,
			            viewsortcols: [true,'horizontal',true],
			            gridview: true,
			            hidegrid: false,
			            caption: 'Indicadores',
	                	editurl:'<?php echo $this->baseUrl() ?>/indicadores/salvar',
	                	forceFit : true

			});
        	$(obj).navGrid(pg,
		        {view:true},
		        {
			        top:20,
			        left:150,
			        dataheight:200,
			        width:400,
			        reloadAfterSubmit:true,
			        jqModal:false, 
			        closeOnEscape:true,
			        closeAfterEdit:true,
			        bottominfo:"Campos marcados com * são obrigatórios"
				}, // edit options
		        {
			        top:20,
			        left:150,
			        dataheight:200,
			        width:400,
			        reloadAfterSubmit:true,
			        jqModal:true, 
			        closeOnEscape:true,
			        closeAfterEdit:true,
			        bottominfo:"Campos marcados com * são obrigatórios",
			        editData: {indicador_configuracao_id:<?php echo $this->indicador_configuracao_id;?>}
			        
							        
				}, // add options
		        {top:20,left:150,reloadAfterSubmit:true,jqModal:false, closeOnEscape:true}, // del options
		        {top:20,left:150,jqModal:false,closeOnEscape:true}, // search options
		        {top:20,left:150,dataheight:200,width:400,jqModal:false,closeOnEscape:true} // view options
    	);
		
	}  

	
    --></script>

