<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'usuarios', 'action'=>'add'));?>' 
			method="post">
<?php echo $this->form->id ;?>
<br>
<?php echo $this->form->username ;?>
<br>
<?php echo $this->form->password ;?>
<br>
<?php echo $this->form->nome ;?>
<br>
<?php echo $this->form->email ;?>
<br>
<?php echo $this->form->grupos ;?>
<br>
<?php echo $this->form->submit ;?>

</form>
