<script type="text/javascript">
<!--
$(function() {
	
	$("#chpass").submit(function(e){
		if($("#password").val()!=$("#confirm").val()){
			alert("Senha não confere")
			return false;
		}
		
		});
	enableTabs();
});
//-->
</script>
<h3>Usuário: <?php echo $this->usuario->nome;?></h3>
<form id='chpass' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'usuarios', 'action'=>'changepassword'));?>' 
			method="post">
	<?php echo $this->form->id;?>
	<?php echo $this->form->password?>
	<?php echo $this->form->confirm?>
	<?php echo $this->form->submit?>
</form>