

<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'grupos', 'action'=>'edit'));?>' 
			method="post">

<table>
	<tr><td width="400px">
	<?php echo $this->form->id;?>
	</td></tr><tr><td>
	<?php echo $this->form->grupo?>
	</td></tr><tr><td>
	<?php echo $this->form->descricao?>
	</td></tr>
	<tr><td>
	<?php echo $this->form->paginas?>
	</td></tr><tr><td>
	<?php echo $this->form->submit?>
	</td></tr>
</table>	
</form>