<p><a href="<?php echo $this->url(array('action'=>'add'));?>">Adicionar Grupo</a></p>
<table>
<tr>
<th>Grupo</th>
<th>Descricao</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->grupos as $grupo) : ?>
<tr>
<td><?php echo $this->escape($grupo->grupo);?></td>
<td><?php echo $this->escape($grupo->descricao);?></td>
<td>

<?php
	/**
	 * os grupos com id até 5 são reservados ao sistema e não podem ser alterados
	 */ 
	if ($grupo->id>5){
?>
	<a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$grupo->id));?>">Editar</a>
	<?php }?>

</td>
</tr>
<?php endforeach; ?>
</table>