<div id="formtabs" style="width: 800px; height:100%">
	<ul>
		<li><a href="#tabs-0" >Operação</a></li>
	</ul>


	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'operacoes', 'action'=>'add'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->form->id ?>
			<?php echo $this->form->meta_id; ?>
			</div>
			<table width="100%" border="0">
			<tr><td>
			<?php echo $this->form->descricao; ?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->submit;?>
			</td></tr>
			</table>
		</form>

	</div>
</div>
<br></br>
<div style="clear:both;">
<a href='<?php echo $this->url(array('controller'=>'plano', 'action'=>'meta'))?>'>Voltar</a>
</div>
