<div id="formtabs" style="height: 100%">
<ul>
	<li><a href="#tabs-0">Programa</a></li>
	<li><a href="#tabs-1">Objetivos</a></li>
	<li><a href="#tabs-2">Metas</a></li>
	<li><a href="#tabs-3">Indicadores</a></li>
</ul>
<div id="tabs-0" style="overflow: hidden">
<form id='<?php
echo $this->form->getId ();
?>'
	enctype='<?php
	echo $this->form->getEnctype ();
	?>'
	action='<?php
	echo $this->url ( array ('controller' => 'programas', 'action' => 'edit' ) );
	?>'
	method="post"><input type="hidden" id="dependents" value="1,2,3" />
<div style='display: none'>
			<?php
			echo $this->form->id?>
			</div>
<table width="100%" border="0">
	<tr>
		<td>
			<?php echo $this->form->descricao;	?>
			</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->form->menu;	?>
		</td>
	</tr>
	<tr>
		<td>

			<?php	echo $this->form->meta;	?>
			</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->form->interfaces;	?>
			</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->form->responsavel_id;		?>
			</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->form->submit;	?>
			</td>
	</tr>
</table>
</form>

</div>

<div id="tabs-1" style="overflow: hidden">
	 <?php
		if (isset ( $this->programa )) {
			?>
		<form id='frmobjetivos'	
			enctype='<?php	echo $this->formDescritivo->getEnctype ();	?>'
			action='<?php	echo $this->url ( array ('controller' => 'programas', 'action' => 'addobjetivo' ) );?>'
			method="post">
		<div style='display: none'>
			<?php echo $this->formDescritivo->id?>
			<input type=hidden name='programa_id'	value='<?php echo $this->programa->id?>'>
		</div>
		<fieldset>
		<div style='clear:both'>
		<?php	echo $this->formDescritivo->descricao;	?>
		</div>
		<?php	echo $this->formDescritivo->submit;	?>
		</fieldset>			
		</form>
<table width="100%" id="tbobjetivos" class='ui-widget ui-widget-panel'>
	<tr>
		<th></th>
		<th>Objetivos</th>
	</tr>
	<?php
			$cycle=$this->cycle(array('ui-state-hover','ui-state-active')); 
			foreach ( $this->programa->findModel_ObjetivosPrograma () as $objetivo ) {
				?>
			<tr class='lst <?php echo $cycle->next()?>'>
		<td><?php	echo $this->lineToolbar ( 'programas', $objetivo )?></td>
		<td><?php	echo $objetivo->descricao;	?></td>
	</tr>
			<?php
			}
			?>
		</table>
		<?php
		}
		?>
		
	
	</div>
	<div id="tabs-2" style="overflow: hidden">
			
			<?php
			if (isset ( $this->programa )) {
				?>
			<form id='frmmetas' enctype='<?php
				echo $this->formDescritivo->getEnctype ();
				?>'
		action='<?php
				echo $this->url ( array ('controller' => 'programas', 'action' => 'addmeta' ) );
				?>'
		method="post">
	        <div style='display: none'>
				<?php
				echo $this->formDescritivo->id?>
				<input type=hidden name='programa_id'
		             value='<?php
				     echo $this->programa->id?>'>
	         </div>
	         <fieldset>
	         <div style='clear:both'>
				<?php echo $this->formDescritivo->descricao; ?>
			</div>
			
				<?php echo $this->formDescritivo->submit;?>
				
				
			</fieldset>			
			</form>
			<br>
			<table width="100%" id="tbmetas" class='ui-widget ui-widget-panel'>
				<tr>
					<th width="5%"></th>
					<th>Metas</th>
				</tr>
				<?php
						foreach ( $this->programa->findModel_MetasPrograma () as $meta ) {
							?>
						<tr class='lst <?php echo $cycle->next()?>'>
							<td><?php echo $this->lineToolbar ( 'programas', $meta )?></td>
							<td><?php echo $meta->descricao; ?></td>
						</tr>
				<?php }	?>
			</table>
					<?php } ?>
	</div>
			<div id="tabs-3" style="overflow: hidden">
				<?php if (isset ( $this->programa )) {	?>
                <div style="clear:both;width:100%;">
				<form id='frmindicadores' enctype='<?php echo $this->frmIndicador->getEnctype ();?>'
					action='<?php echo $this->url ( array ('controller' => 'programas', 'action' => 'addindicador' ) );	?>'
					method="post">
					<div style='display: none'>
						<?php echo $this->frmIndicador->id?>
						<input type=hidden name='programa_id' value='<?php echo $this->programa->id?>'>
					</div>
					
					<fieldset>
					<div style='clear:both'>
					<?php echo $this->frmIndicador->descricao;?>
					<br>
					
					
					<?php echo $this->frmIndicador->tipo_indicador_id;	?>			
					</div>
					<?php echo $this->formDescritivo->submit;?>
					
					</fieldset>			
				</form>
                </div>
				
                
				<table width="100%" id="tbindicadores" class='ui-widget ui-widget-panel' >
					<tr>
						<th style="width: 2%"></th>
						<th style="width: 2%"></th>
						<th>Indicadores</th>
					</tr>
				<?php 
				foreach ( $this->programa->findManyToManyRowset ( 'Model_Indicadores', 'Model_IndicadoresPrograma' ) as $indicador ) {
					if($indicador->situacao_id==1){	
				?>
						<tr class='lst <?php echo $cycle->next()?>'>
						<td style="width: 2%"><?php	echo $this->lineToolbar ( 'programas', $indicador )?></td>
						<td style="width: 2%"><?php	echo $this->indicadoresToolbar ( $indicador )?>	</td>
						<td align="left"><?php echo $indicador->descricao;	?></td>
					</tr>
					
				<?php
						}	
				} ?>
		      </table>
              
	<?php }	?>
	</div>
</div>
<br></br>
<p></p>
<a	href='<?php	echo $this->url ( array ('controller' => 'plano', 'action' => 'programas' ) )?>'>Voltar</a>
<br>