<div id="formtabs" style="width: 800px; height: 100%">
<ul>
	<li><a href="#tabs-0">Programa</a></li>
	<li><a href="#tabs-1">Objetivos</a></li>
	<li><a href="#tabs-2">Metas</a></li>
	<li><a href="#tabs-3">Indicadores</a></li>
</ul>
<div id="tabs-0" style="overflow: hidden">
<form id='<?php
echo $this->form->getId ();
?>'
	enctype='<?php
	echo $this->form->getEnctype ();
	?>'
	action='<?php
	echo $this->url ( array ('controller' => 'programas', 'action' => 'edit' ) );
	?>'
	method="post"><input type="hidden" id="dependents" value="1,2,3" />
<div style='display: none'>
			<?php
			echo $this->form->id?>
			</div>
<table width="100%" border="0">
	<tr>
		<td>
			<?php
			echo $this->form->descricao;
			?>
			</td>
	</tr>
	<tr>
		<td>
			<?php
			echo $this->form->menu;
			?>
		</td>
	</tr>
	<tr>
		<td>

			<?php
			echo $this->form->meta;
			?>
			</td>
	</tr>
	<tr>
		<td>
			<?php
			echo $this->form->interfaces;
			?>
			</td>
	</tr>
	<tr>
		<td>
			<?php
			echo $this->form->responsavel_id;
			?>
			</td>
	</tr>
	<tr>
		<td>
			<?php
			echo $this->form->submit;
			?>
			</td>
	</tr>
</table>
</form>

</div>

<div id="tabs-1" style="overflow: hidden">
	 <?php
		if (isset ( $this->programa )) {
			?>
		<form id='frmobjetivos'
	enctype='<?php
			echo $this->formDescritivo->getEnctype ();
			?>'
	action='<?php
			echo $this->url ( array ('controller' => 'programas', 'action' => 'addobjetivo' ) );
			?>'
	method="post">
<div style='display: none'>
			<?php
			echo $this->formDescritivo->id?>
			<input type=hidden name='programa_id'
	value='<?php
			echo $this->programa->id?>'></div>
			<?php
			echo $this->formDescritivo->descricao;
			?>
			<?php
			echo $this->formDescritivo->submit;
			?>			
		</form>
<table width="100%" id="tbobjetivos" class='ui-widget ui-widget-panel'>
	<tr>
		<th></th>
		<th>Objetivos</th>
	</tr>
	<?php
			foreach ( $this->programa->findModel_ObjetivosPrograma () as $objetivo ) {
				?>
			<tr>
		<td><?php
				echo $this->lineToolbar ( 'programas', $objetivo )?></td>
		<td><?php
				echo $objetivo->descricao;
				?></td>
	</tr>
			<?php
			}
			?>
		</table>
<button>Proximo >></button>
		<?php
		}
		?>
		
	
	</div>
<div id="tabs-2" style="overflow: hidden">
		
		<?php
		if (isset ( $this->programa )) {
			?>
		<form id='frmmetas'
	enctype='<?php
			echo $this->formDescritivo->getEnctype ();
			?>'
	action='<?php
			echo $this->url ( array ('controller' => 'programas', 'action' => 'addmeta' ) );
			?>'
	method="post">
<div style='display: none'>
			<?php
			echo $this->formDescritivo->id?>
			<input type=hidden name='programa_id'
	value='<?php
			echo $this->programa->id?>'></div>
			<?php
			echo $this->formDescritivo->descricao;
			?>
			
			<?php
			echo $this->formDescritivo->submit;
			?>			
		</form>
<br>
<table width="100%" id="tbmetas" class='ui-widget ui-widget-panel'>
	<tr>
		<th>Metas</th>
	</tr>
	<?php
			foreach ( $this->programa->findModel_MetasPrograma () as $meta ) {
				?>
			<tr>
		<td><?php
				echo $this->lineToolbar ( 'programas', $meta )?></td>
		<td><?php
				echo $meta->descricao;
				?></td>
	</tr>
			<?php
			}
			?>
		</table>
		<?php
		}
		?>
	</div>
<div id="tabs-3" style="overflow: hidden">
		
		
		<?php
		if (isset ( $this->programa )) {
			?>
		<form id='frmindicadores'
			enctype='<?php echo $this->frmIndicador->getEnctype ();?>'
			action='<?php echo $this->url ( array ('controller' => 'programas', 'action' => 'addindicador' ) );	?>'
			method="post">
			<div style='display: none'>
				<?php echo $this->frmIndicador->id?>
				<input type=hidden name='programa_id' value='<?php echo $this->programa->id?>'>
			</div>
			<?php
			echo $this->frmIndicador->descricao;
			?>
			<br></br>
			<?php
			echo $this->frmIndicador->tipo_indicador_id;
			?>			
			<?php
			echo $this->frmIndicador->submit;
			?>			
		</form>
<br>
<table width="100%" id="tbindicadores" class='ui-widget ui-widget-panel'>
	<tr>
		<th style="width: 2%"></th>
		<th style="width: 2%"></th>
		<th>Indicadores</th>

	</tr>
	<?php
			foreach ( $this->programa->findManyToManyRowset ( 'Model_Indicadores', 'Model_IndicadoresPrograma' ) as $indicador ) {
				?>
		<tr>
		<td style="width: 2%"><?php
				echo $this->lineToolbar ( 'programas', $indicador )?></td>
		<td style="width: 2%"><?php
				echo $this->indicadoresToolbar ( $indicador )?>
		</td>
		<td align="left"><?php
				echo $indicador->descricao;
				?></td>
	</tr>
			<?php
			}
			?>
		</table>
		<?php
		}
		?>
	</div>
</div>
<br></br>
<p></p>
<a
	href='<?php
	echo $this->url ( array ('controller' => 'plano', 'action' => 'programas' ) )?>'>Voltar</a>
<br>