<div class="outer">
<?php echo $this->myToolbar();?>
<div id="tabela" class='inner'>
<br></br>
<table width="100%">
<caption class="titulos-tabela">Programas</caption>
<thead class="titulos-tabela">
<th>Descrição</th>
<th>Realiz.</th>
<th>Relatório</th>
</thead>
<tbody>
	<?php foreach ($this->programas as $programa){?>
	<tr bgcolor="#ece9d8">
		<td class="texto">
			<a href='<?php echo $this->url(array('controller'=>'projetos','action'=>'index', 'programa_id'=>$programa->id));?>'>
				<?php echo $programa->descricao;?>
			</a>
		</td>
		<td></td>
		<td><img alt="relatório" src="<?php echo $this->baseUrl();?>/images/impressora.gif"/> </td>
	</tr>
	<?php }?>
</tbody>
</table>
<br></br>
</div>
</div>

</div>