<div id="formtabs">
    <ul>
        <li><a href="#tabs-0">Projeto</a></li>
    </ul>
    <div id="tabs-0" style="overflow: hidden">
        <form id='<?php echo $this->form->getId();?>'
              enctype='<?php echo $this->form->getEnctype();?>'
              action='<?php echo $this->url(array('action' => 'save'));?>?format=json'
              method="post">
            <input type="hidden" id="dependents" value="1,2,3" />
            <div style='display:none'>
			
			<?php echo $this->form->projeto->getDisplayGroup('ident')?>
			</div>
            <table width="100%" border="0">
                <tr>
                    <td>
						<?php echo $this->form->projeto->descricao; ?>
                    </td>
                </tr>
                <tr>
                    <td>
						<?php echo $this->form->projeto->menu; ?>
                    </td>
                </tr>
                <tr>
                    <td>
						<?php echo $this->form->projeto->setor_id; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $this->form->submit; ?>
                        <?php echo $this->form->cancelar; ?>
                    </td>
                </tr>
            </table>
        </form>
    </div>

    </div>