
<table id="tb-setores"></table>
<div id="pg-setores"></div>

<div class="contextMenu" id="MenuSetores" >
    <ul class="cm-ul ui-widget">
        <li id="add" >
            <span style="float:left" class="ui-icon ui-icon-document"></span> Novo
        </li>
        <li style="" class="ui-widget-shadow ui-separator ui-state-hover"></li>
        <li id="edit" >
            <span style="float:left" class="ui-icon ui-icon-pencil"></span> Editar
        </li>
        <li id="delete">
            <span style="float:left" class="ui-icon ui-icon-trash"></span>Apagar
        </li>
    </ul>
</div>
<div class="contextMenu" id="MenuSetores-geral" >
    <ul class="cm-ul ui-widget">
        <li id="add" >
            <span style="float:left" class="ui-icon ui-icon-document"></span> Novo
        </li>
    </ul>
</div>

<script type="text/javascript" >
<?php include_once'index.js';?>
$(function(){
	//$.getScript('<?php echo $this->url();?>?format=js', function(r){
	    setores = new Setores();
	    setores.init();
	    setores.createGrid();
		//});

});
</script>