<script type="text/javascript">
<?php    include_once 'index.js'; ?>
$(document).ready(function(){
    usuarios = new Usuarios();
    usuarios.init();
    usuarios.createGrid();
	
});
</script>


<div id="formtabs" style="min-height: 200px">
<ul>
	<li><a href="#tabs-0"><b>Ativos</b></a></li>
	<li><a href="#tabs-1"><b>Excluídos</b></a></li>
</ul>


<div id="tabs-0" style="overflow: hidden">
	<table  id="habilitados">
	</table>
	<div id="pager_habilitados" class="scroll" style="text-align:center;"></div>
	
</div>
<div id="tabs-1" style="overflow: hidden">	
	<table  id="excluidos">
	</table>
	<div id="pager_excluidos" class="scroll" style="text-align:center;"></div>
	<input type='hidden' id='parametros_excluidos' value='situacao_id/2'/>

</div>
</div>
