<div id="formtabs" style="width: 800px; height:100%">
	<ul>
		<li><a href="#tabs-0" >Projeto</a></li>
		<li><a href="#tabs-1">Objetivos</a></li>
		<li><a href="#tabs-2">Metas</a></li>
		<li><a href="#tabs-3">Indicadores</a></li>
	</ul>
	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>' 
			action='<?php echo $this->url(array('controller'=>'projetos', 'action'=>'edit'));?>' 
			method="post">
			
			<input type="hidden" id="dependents" value="1,2,3"/>
			<div style='display:none'>
			
			<?php echo $this->form->getDisplayGroup('ident')?>
			</div>
			<table width="100%" border="0">
			<tr><td>
			<?php echo $this->form->descricao;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->menu;?>
			<?php echo $this->form->meta;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->interfaces;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->responsavel_id;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->submit;?>
			</td></tr>
			</table>
		</form>

	</div>

	<div id="tabs-1" style="overflow: hidden">
	 <?php if(isset($this->projeto)){ ?>
		<form id='frmobjetivos' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'projetos', 'action'=>'addobjetivo'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='projeto_id' value='<?php echo $this->projeto->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<table width="100%" id="tbobjetivos" class='ui-widget ui-widget-panel'>
			<tr>
				<th width="5%"></th>
				<th>Objetivos</th>
			</tr>
	<?php  
			foreach($this->projeto->findModel_ObjetivosProjeto() as $objetivo){
	?>
			<tr>
					<td><?php echo $this->lineToolbar('projetos',$objetivo)?></td>
				<td><?php echo $objetivo->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
	</div>
	<div id="tabs-2" style="overflow: hidden">
		
		<?php if(isset($this->projeto)){ ?>
		<form id='frmmetas' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'projetos', 'action'=>'addmeta'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='projeto_id' value='<?php echo $this->projeto->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<br>
		<table width="100%" id="tbmetas" class='ui-widget ui-widget-panel'>
			<tr>
				<th width="5%"></th>
				<th>Metas</th>
			</tr>
	<?php  
			foreach($this->projeto->findModel_MetasProjeto() as $meta){
	?>
			<tr >
				<td><?php echo $this->lineToolbar('projetos',$meta)?></td>
				<td><?php echo $meta->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
	</div>

	<div id="tabs-3" style="overflow: hidden">
		
		<?php if(isset($this->projeto)){ ?>
		<form id='frmindicadores' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'projetos', 'action'=>'addindicador'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='projeto_id' value='<?php echo $this->projeto->id?>'>
			</div>
			<?php echo $this->formDescritivo->descricao;?>
			
			<?php echo $this->formDescritivo->submit;?>			
		</form>	
		<br>
		<table width="100%" id="tbindicadores" class='ui-widget ui-widget-panel'>
			<tr>
				<th width="2%"></th>
				<th width="2%"></th>
				<th>Indicadores</th>
			</tr>
	<?php  
			foreach($this->projeto->findManyToManyRowset('Model_Indicadores', 'Model_IndicadoresProjeto') as $indicador){
	?>
			<tr>
				<td width="2%"><?php echo $this->lineToolbar('projetos',$indicador)?></td>
				<td width="2%"><?php echo $this->indicadoresToolbar($indicador) ?></td>
				<td><?php echo $indicador->descricao;?></td>
			</tr>
			<?php }?>
			
		</table>
		<?php }?>
	</div>
<a href='<?php echo $this->url(array('controller'=>'plano','action'=>'programa'));?>'>Voltar</a>
</div>
<br></br>
<p></p>