
<table id="tb-cargos"></table>
<div id="pg-cargos"></div>

<div class="contextMenu" id="MenuJqGrid" >
    <ul class="cm-ul ui-widget">
        <li id="add" >
            <span style="float:left" class="ui-icon ui-icon-plus"></span> Adicionar Nível
        </li>
        <li style="" class="ui-widget-shadow ui-separator ui-state-hover"></li>
        <li id="edit" >
            <span style="float:left" class="ui-icon ui-icon-trash"></span> Editar
        </li>
        <li id="delete">
            <span style="float:left" class="ui-icon ui-icon-plus"></span>Apagar
        </li>
    </ul>
</div>
<script type="text/javascript" >
<?php 
include('index.js');
?>
</script>