<div class="ui-overlay ui-corner-all" style="width: 680px;">
	<h3><?php echo $this->indicador->descricao;?></h3>
	
	<?php
	 $fmt = new NumberFormatter('pt_BR', NumberFormatter::DECIMAL );
	foreach($this->indicadores_configs as $config){
		$periodo = $config->findParentRow('Model_TiposPeriodos');
		$resultados = $config->findDependentRowset('Model_IndicadoresResultados');
		$campos = explode(',',$config->campos);
	?>
	
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header tabela-resultado'  >
		<caption><h3>Indicador <?php echo $periodo->descricao;?> </h3></caption>
		<tr>
			<th>Competência</th>
			<?php if(in_array('n', $campos)){?>
				<th>Numerador</th>
			<?php }?>
			
			<?php if(in_array('d', $campos)){?>
				<th>Denominador</th>
			<?php }?>	
			<th>Resultado</th>
		</tr>
		<?php foreach($resultados as $resultado){
			if($config->tipo_periodo_id==1){
        		$competencia =substr ( $resultado->competencia,4,2)."/".substr ( $resultado->competencia, 0, 4 );
        		
        	}else{
        		$competencia = $resultado->competencia;
        	} 
		?>
		<tr class='<?php echo $this->cycle(array("odd","even"))->next()?>"'>
			<td><?php echo $competencia;?></td>
			<?php if(in_array('n', $campos)){?>
				<td><?php echo $resultado->numerador;?></td>
			<?php }?>
			<?php if(in_array('d', $campos)){?>
				<td><?php echo $resultado->denominador;?></td>
			<?php }?>
			
			<?php if($config->base==1){?>
				<td><?php echo $resultado->resultado;?></td>
			<?php }else{?>
				<td><?php echo $fmt->format($resultado->resultado);?></td>
			<?php }?>
		</tr>
		<?php }?>
	</table>
	<div style='clear:both'>
	
	<?php
		$acl = Zend_Registry::get('acl');
		$auth = Zend_Auth::getInstance();
		
		if ($auth->hasIdentity ()) {
			$role = $auth->getIdentity ()->username;
		} else {
			$role = 'guest';
		}
		$resource = 'indicadores';
		if (! $acl->has ( $resource )) 
			$resource = null;

		if($acl->isAllowed($role,$resource,'editar') ||	!$resource)
		{		
	?>
		<a href='<?php echo $this->url(array('controller'=>'indicadores','action'=>'edit', 
						'id'=>$this->indicador->id,'indicador_configuracao_id'=>$config->id));?>'
						title='Editar valores' 
						class='fg-button ui-state-default fg-button-icon-left ui-corner-all'>
						<span class='ui-icon ui-icon-pencil'>Editar</span>Editar
		</a>
		<?php }?>
	</div>
	<br/>
	<img src="<?php echo $this->url(array('controller'=>'indicador','action'=>'grafico', 'indicador_configuracao_id'=>$config->id))?>"  alt="gráfico"/>
        	
	<br/>
	<hr/>
	<?php }?>
	
	<a href="javascript:window.history.go(-1)">Voltar</a>
	
</div>



	
	
	