
<div id="formtabs">
	<ul>
		<li><a href="#tabs-0" >Objetivo Específico</a></li>
		<li><a href="#tabs-1">Estratégias</a></li>
		<li><a href="#tabs-2">Parcerias</a></li>
	</ul>
	<div id="tabs-0" style="overflow: hidden">
		<form id='<?php echo $this->form->getId() ;?>' enctype='<?php echo $this->form->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'objetivos-especificos', 'action'=>'save'));?>' 
			method="post">
			<input type="hidden" id="dependents" value="1,2"/>
			<div style='display:none'>
			<?php echo $this->form->getDisplayGroup('ident') ?>
			</div>
			<table width="100%" border="0">
			<tr><td>
			<?php echo $this->form->descricao;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->menu;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->recursos;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->cronograma;?>
			</td></tr>
			<tr><td>
			<?php echo $this->form->submit;?>
			</td></tr>
			</table>
		</form>

	</div>


	<div id="tabs-1" style="overflow: hidden">

		<?php if(isset($this->objetivo_especifico)){ ?>
		<form id='frmestrategias' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'objetivos-especificos', 'action'=>'addestrategia'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='objetivo_especifico_id' value='<?php echo $this->objetivo_especifico->id?>'>
			</div>
			<fieldset>
				<div style='clear:both'>
					<?php echo $this->formDescritivo->descricao;?>
					
					<?php echo $this->selectobjetivos?>
				</div>
				
			<?php echo $this->formDescritivo->submit;?>
			</fieldset>			
		</form>	
		<br>
		<table width="100%" id="tbestrategias" class='ui-widget ui-widget-panel'>
			<tr>
				<th width="5%"></th>
				<th>Estratégias</th>
			</tr>
	<?php  
			foreach($this->objetivo_especifico->findModel_Estrategias() as $estrategia){
				if($estrategia->situacao_id==2) continue;
	?>
			<tr class='lst'>
				<td><?php echo $this->lineToolbar('objetivos-especificos',$estrategia)?></td>
				<td><?php echo $estrategia->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
		

		
	</div>

	<div id="tabs-2" style="overflow: hidden">
		
		<?php if(isset($this->objetivo_especifico)){ ?>
		<form id='frmparcerias' enctype='<?php echo $this->formDescritivo->getEnctype();?>'
			action='<?php echo $this->url(array('controller'=>'objetivos-especificos', 'action'=>'addparceria'));?>' 
			method="post">
			<div style='display:none'>
			<?php echo $this->formDescritivo->id ?>
			<input type=hidden name='objetivo_especifico_id' value='<?php echo $this->objetivo_especifico->id?>'>
			</div>
			<fieldset>
				<div style='clear:both'>
				<?php echo $this->formDescritivo->descricao;?>
				</div>
			<?php echo $this->formDescritivo->submit;?>
			</fieldset>			
		</form>	
		<br>
		<table width="100%" id="tbparcerias" class='ui-widget ui-widget-panel'>
			<tr>
				<th width="5%"></th>
				<th>Parceria</th>
			</tr>
	<?php  
			foreach($this->objetivo_especifico->findModel_Parcerias() as $parceria){
				if($parceria->situacao_id==2) continue;
	?>
			<tr class='lst'>
				<td><?php echo $this->lineToolbar('objetivos-especificos',$parceria)?></td>
				<td><?php echo $parceria->descricao;?></td>
			</tr>
			<?php }?>
		</table>
		<?php }?>
	</div>
	<a href='<?php echo $this->url(array('controller'=>'plano', 'action'=>'projeto'))?>'>Voltar</a>
</div>