

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget-header ui-state-highlight tb-header '>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>($this->nivel=='Acao')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		
	</table>
	
	<br></br>

	<br></br>
	<?php if($this->acao){	
		
	?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header" style="text-align: left"><?php echo $this->acao->descricao;?></caption>
			<thead class="ui-widget ui-widget-header">
				<tr>
					
					<td class="ui-widget ui-widget-header">Objetivos</td>
					<td>Estratégias</td>
					<td>Metas</td>
					<td>Realiz</td>
					
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				
				<tr >
					<td width="30%">
						<ul>
						<?php
						$select = $this->acao->select();
						$select->order('id'); 
						foreach ($this->acao->findDependentRowset('Model_ObjetivosAcao',null,$select) as $objetivo){?>
							<li><?php echo $objetivo->descricao;?></li>
						<?php }?>
						</ul>
					</td>
					<td width='30%'>
						<ul>
						<?php
						$select = $this->acao->select();
						$select->order('id'); 
						foreach ($this->acao->findDependentRowset('Model_EstrategiasAcao',null,$select) as $estrategia){?>
							<li><?php echo $estrategia->descricao;?></li>
						<?php }?>
						</ul>
					</td>
					<td width='30%'>
						<ul>
						<?php
						$select = $this->acao->select();
						$select->order('id'); 
						foreach ($this->acao->findDependentRowset('Model_MetasAcao',null,$select) as $meta){?>
							<div style="float: left;width: 80%">
								<?php echo $meta->descricao;?>
								</div>
								 <div style="float: left;width: 18%">
								 	<div id="pb-metaacao-<?php echo $meta->id;?>" class="progressbar"></div>
								 </div>
							 
						<?php }?>
						</ul>
					</td>
					<td><div id="pb-acao-<?php echo $acao->id;?>" class="progressbar"></div></td>
				</tr>
				
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>




</div>