

<div class="ui-overlay ui-corner-all">

	<!--INICIO DA TABELA COM BORDA ARREDONDADAS-->

	<table width="99%" border="0" cellpadding="0" cellspacing="0" style="padding: 0px;">
	  <tr>
	       <td width="5" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-esq.jpg"  style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td background="<?php echo $this->baseUrl (); ?>/images/linha-sup-horiz.jpg" style="background-repeat:repeat-x">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td width="11" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-dir.jpg" style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	  </tr>
	  <tr valign="top">
	       <td valign="top" background="<?php echo $this->baseUrl (); ?>/images/linha-esq-vert.jpg"  style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" /></td>
	   <td class="titulos-miolo">

	<!--  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header' -->
	<table cellpadding="0" cellspacing="0">
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'), 
													 'label'=>'Objetivo Específico', 'acao'=>'objetivos-especificos', 
													 'campo_id'=>'objetivo_especifico_id' ));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->operacao,
													 'nome'=>'Operacao', 'label'=>'Operação', 'acao'=>'operacao', 'campo_id'=>'operacao_id', 'detalhar'=>false));?>
		
	</table>
	
<!--FIM DA TABELA COM BORDAS ARREDONDADAS-->	</td>
      <td background="<?php echo $this->baseUrl (); ?>/images/linha-dir-vert.jpg" style="background-repeat:repeat-y">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	  </td>
   </tr>
   <tr>
    <td width="5" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-esq.jpg"  style="background-repeat:no-repeat">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
    <td background="<?php echo $this->baseUrl (); ?>/images/linha-inf-horiz.jpg" style="background-repeat:repeat-x"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
    <td width="11" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-dir.jpg"  style="background-repeat:no-repeat">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
  </tr>
</table>
<br>
<br>
	<table>
		<tr>
			<th><font size="2">Atividade</font></th>
			<td><font size="2"><?php echo $this->atividade->descricao?></font></td>
		</tr>
		<tr>
			<th><font size="2">Responsável</font></th>
			<td><font size="2"><?php echo $this->atividade->responsavel?></font></td>
		</tr>
		<tr>
			<th><font size="2">Intersecao</font></th>
			<td><font size="2"><?php echo $this->atividade->intersecao?></font></td>
		</tr>
		<tr>
			<th><font size="2">Início</font></th>
			<td><font size="2"><?php echo $this->atividade->inicio_data?></font></td>
		</tr>
		<tr>
			<th><font size="2">Prazo Inicial</font></th>
			<td><font size="2"><?php echo $this->atividade->prazo_data?></font></td>
		</tr>
		<tr>
			<th><font size="2">Prazo Atual</font></th>
			<td><font size="2">
			<?php
			$prazo = '';
			foreach($this->atividadeprazo as $atividadeprazo){ 
				$prazo =  new Zend_Date($atividadeprazo->prazo_data,Zend_Date::ISO_8601);
			}
			if ($prazo){
				echo $prazo->toString('dd/MM/yyyy');
			}
			?>
			</font></td>
		</tr>
		<tr>
			<th><font size="2">Andamento<br>da Execução</font></th>
			<td><font size="2"><?php echo $this->atividade->andamento?></font></td>
		</tr>
		
	</table>
<br>
	<table border="2">
	<tr>
	<td colspan="2"><font size="2"><b>PRAZOS</b></font></td>
	</tr>
	<tr>
	<td><font size="2"><b>Prazo</b></font></td>
	<td><font size="2"><b>Motivo do Novo Prazo</b></font></td>
	</tr>
	<?php
	foreach($this->atividadeprazo as $atividadeprazo){ 
	?>
		<tr>
		<td><font size="2">
		<?php 
		$prazo =  new Zend_Date($atividadeprazo->prazo_data,Zend_Date::ISO_8601);
		echo $prazo->toString('dd/MM/yyyy');
		?>
		</font></td>
		<td><font size="2"><?php echo $atividadeprazo->motivopostergacao; ?></font></td>
		</tr>
	<?php 	
	}?>

		<tr>
		<td colspan="2">
		<?php 
				$mysession = new Zend_Session_Namespace ( 'mysession' );
				$acl = $mysession->acl;
		
				$auth = Zend_Auth::getInstance();
				if ($auth->hasIdentity ()) {
					$role = $auth->getIdentity ()->username;
				} else {
					$role = 'guest';
				}
		
				if (! $acl->has ( $resource )) 
					$resource = null;
		
				if($acl->isAllowed($role,$resource) ||
						!$resource){ 
					echo "<a href='".$this->url(array('controller'=>'atividades','action'=>'addprazo', 'id'=>$this->atividade->id))."'
							title='Adicionar Prazo' 
							class='fg-button ui-state-default fg-button-icon-left ui-corner-all'>
							<span class='ui-icon ui-icon-plus'>Adicionar Projeto</span>Adicionar Prazo</a>";
				}
		?>

		</td>
		</tr>

	</table>


</div>