	<?php
	$lC=0;
	$this->campo_id = isset($this->campo_id) ? $this->campo_id : strtolower($this->nome).'_id'; 
	$href = $this->url(array('controller'=>'plano',
												'action'=>strtolower($this->nome) ,
												$this->campo_id=>$this->objeto->id));
    $this->label = isset($this->label) ? $this->label : $this->nome;	
     											
	?>
		<tr style="border-bottom: thin solid black"  class="even">
			<td class='removedui-widget-header text-header'><?php echo $this->label?></td>
			<td class='removedui-state-highlight' style='padding-left:15px'>
				<a href='<?php echo $href?>' style="float:left"> <?php echo $this->objeto->descricao?></a>
				<div id="pb-<?php echo $this->nome?>-<?php echo $this->objeto->id;?>" class="progressbar" style="float:right;width: 100px;"></div>
			</td>
		</tr>
		<?php 
		
		 if($this->detalhar){?>
			<tr style="border-bottom: thin solid black" class="odd">	
				<td class='removedui-widget-header text-header' >Objetivos do <?php echo $this->nome?></td>
				<td class='removedui-state-highlight' style='padding-left:15px'>
				<?php 
					foreach($this->objeto->findDependentRowset('Model_Objetivos'.$this->nome) as $objetivo){
						echo '<li>'.$objetivo->descricao.'</li>';
					}
				?>
				
				</td>
			</tr>
			<tr style="border-bottom: thin solid black" class="even"> 	
				<td class='removedui-widget-header text-header'  >Metas do <?php echo $this->nome?></td>
				<td class='removedui-state-highlight' style='padding-left:15px'>
				<?php 
					foreach($this->objeto->findDependentRowset('Model_Metas'.$this->nome) as $meta){
						echo '<li>'.$meta->descricao.'</li>';
					}
				?>
				
				</td>
			</tr>


			<tr style="border-bottom: thin solid black" class="odd"> 	
				<td class='removedui-widget-header text-header'  >Indicadores do <?php echo $this->nome?></td>
				<td class='removedui-state-highlight' style='padding-left:15px'>
				<?php 
					foreach($this->objeto->findManyToManyRowset('Model_Indicadores', 'Model_Indicadores'.$this->nome) as $indicador){
						echo '<li>'.$indicador->descricao.'</li>';
					}
				?>
				
				</td>
			</tr>
			<tr style="border-bottom: thin solid black"  class="even">
				<td class='removedui-widget-header text-header'>Interfaces</td>
				<td class='removedui-state-highlight' style='padding-left:15px'>
					<?php echo $this->objeto->interfaces?>
				</td>
			</tr>

			
			 <tr style="border-bottom: thin solid black" class="odd">
				 <td colspan="2">
				 <?php echo $this->myToolbar(strtolower($this->nome).'s','top',$this->objeto->id);?>
				 </td>
			 </tr>
		 <?php
		}
		?>
	