	<?php
	$lC=0;
	$this->campo_id = isset($this->campo_id) ? $this->campo_id : strtolower($this->nome).'_id'; 
	$href = $this->url(array('controller'=>'plano',
                                'action'=>strtolower($this->acao) ,
                                $this->campo_id=>$this->objeto->id));
        $this->label = isset($this->label) ? $this->label : $this->nome;
     											
	?>
		<tr style="border-bottom: thin solid black"  >
			<td class='text-header' width="13%"><div class="titulo-nivel2"><?php echo $this->label?></div></td>
			<td style='padding-left:15px'>
				<a href='<?php echo $href?>' style="float:left"> <?php echo $this->objeto->descricao?></a>
			</td>
		</tr>
		<?php 
		 if($this->detalhar){
		 	if ((strtolower($this->nome) == "programa")||(strtolower($this->nome) == "projeto")){
			 	?>
				
				<tr style="border-bottom: thin solid black" > 	
					<td class='text-header'  ><div class="subtitulos-descreve-niveis">INDICADORES DO <?php echo strtoupper($this->nome); ?>:</div></td>
					<td  style='padding-left:15px'>
					<?php 
						foreach($this->objeto->findManyToManyRowset('Model_Indicadores', 'Model_Indicadores'.$this->nome) as $indicador){
							if($indicador->situacao_id==2) continue; 
						?>
							<li>
								<div class="texto-descreve-niveis">
									<?php echo $this->cabecalhoIndicador($indicador,strtolower($this->nome))?>
								</div>
							</li>
					<?php 	
						}
					?>
					
					</td>
				</tr>
				<tr style="border-bottom: thin solid black"  c>
					<td ><div class="subtitulos-descreve-niveis">INTERFACES:</div></td>
					<td style='padding-left:15px'>
						<div class="texto-descreve-niveis"><?php echo $this->objeto->interfaces?></div>
					</td>
				</tr>
				<?php 
		 	} // programas e projetos
		 	?>
		 	<?php 
		 	if (strtolower($this->nome)== "objetivo_especifico"){
		 		?>
				<tr style="border-bottom: thin solid black" > 	
					<td class='text-header'  ><div class="subtitulos-descreve-niveis">ESTRATÉGIAS:</div></td>
					<td style='padding-left:15px'>
					<?php 
						$select = $this->objeto->select();
						$select->order('id');
						$select->where('situacao_id=1'); 
						foreach ($this->objeto->findDependentRowset('Model_Estrategias',null,$select) as $estrategia){
						?>
							<li><div class="texto-descreve-niveis"><?php echo $estrategia->descricao;?></div></li>
						<?php }
					?>
					</td>
				</tr>
				
				<tr  >
					<td><div class="subtitulos-descreve-niveis">PARCERIAS:</div></td>

					<td   style='padding-left:15px'>
						<?php
						$select = $this->objeto->select();
						$select->order('id'); 
						$select->where('situacao_id=1');
						foreach ($this->objeto->findDependentRowset('Model_Parcerias',null,$select) as $parceria){
						?>
							<li><div class="texto-descreve-niveis"><?php echo $parceria->descricao;?></div></li>
						<?php }?>
					</td>
				</tr>
				
				
				<?php 
		 	} // objetivo específico
		 	?>
			<tr style="border-bottom: thin solid black" class="ui-state-default">
				 <td colspan="2">
				 <?php echo $this->myToolbar(strtolower($this->nome).'s','top',$this->objeto->id);?>
				 </td>
			</tr>
		 <?php
		}
		?>
	