<?php 
/*
 * meta.phtml
 * @author Hugo
 */
?>

<div class="ui-overlay ui-corner-all">
	<?php // echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'), 
													 'label'=>'Objetivo Específico', 'acao'=>'objetivos-especificos', 
													 'campo_id'=>'objetivo_especifico_id' ));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
		
	</table>
	


	<br><br>

	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="98%">
				<thead class="ui-widget removedui-widget-header">
				<tr>
				<td></td>
				<td colspan="3">
				<div class="titulos-tabela">OPERAÇÕES</div>
				</td>
				</tr>

				<tr class="even">
					<td width="4px"><?php echo $this->myToolbar('operacoes','toptable');?></td>
					<td class="subtitulos-tabela">Descrição</td>
					<td class="subtitulos-tabela" width="70px;">Realiz.</td>
					<td class="subtitulos-tabela" width="40px" align="center"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->operacoes as $operacao){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'operacoes' , 'line', $operacao->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'operacao', 'operacao_id' => $operacao->id ) );?>'>
							<?php echo $operacao->descricao;?>
						</a>
					</div>
					</td>
					<td><div id="pb-operacao-<?php echo $operacao->id;?>" class="progressbar"></div></td>
					<td align="center">
						<a href="#">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
			   	<tr>
			   	<td></td>
		       	<td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
		       	</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	
	


</div>