<?php 
/*
 * meta.phtml
 * @author Hugo
 */
?>

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget ui-widget-content tb-header '>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>($this->nivel=='Projeto')));?>

		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>false, 
													 'label'=>'Objetivo Específico',
													 'campo_id'=>'objetivo_especifico_id' ));?>

		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'detalhar'=>false));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		
	</table>
	


	<br><br>

	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget removedui-widget-header"><b>Operações</b></caption>
			<thead class="ui-widget removedui-widget-header">
				<tr class="odd">
					<td width="40px"><?php echo $this->myToolbar('operacoes','toptable');?></td>
					<td >Descrição</td>
					<td width="100px;">Realiz.</td>
					<td>Relat.</td>
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->operacoes as $operacao){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'operacoes' , 'line', $operacao->id  );?>
					</td>
					<td class="texto">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'operacao', 'operacao_id' => $operacao->id ) );?>'>
							<?php echo $operacao->descricao;?>
						</a>
					</td>
					<td width='10px'><div id="pb-operacao-<?php echo $operacao->id;?>" class="progressbar"></div></td>
					<td width='10px'>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	
	


</div>