<?php 
/*
 * meta.phtml
 * @author Hugo
 */
?>

<div class="ui-overlay ui-corner-all">
	<?php // echo $this->planoNavegacao($this->programa) ;?>
	<!--INICIO DA TABELA COM BORDA ARREDONDADAS-->

	<table width="99%" border="0" cellpadding="0" cellspacing="0" style="padding: 0px;">
	  <tr>
	       <td width="5" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-esq.jpg"  style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td background="<?php echo $this->baseUrl (); ?>/images/linha-sup-horiz.jpg" style="background-repeat:repeat-x">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td width="11" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-dir.jpg" style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	  </tr>
	  <tr valign="top">
	       <td valign="top" background="<?php echo $this->baseUrl (); ?>/images/linha-esq-vert.jpg"  style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" /></td>
	   <td class="titulos-miolo">



	<table width="100%" cellpadding="0" cellspacing="0">
	<!--  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header' -->
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'), 
													 'label'=>'Objetivo Específico', 'acao'=>'objetivos-especificos', 
													 'campo_id'=>'objetivo_especifico_id' ));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
		
	</table>
<!--FIM DA TABELA COM BORDAS ARREDONDADAS-->	</td>
      <td background="<?php echo $this->baseUrl (); ?>/images/linha-dir-vert.jpg" style="background-repeat:repeat-y">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	  </td>
   </tr>
   <tr>
    <td width="5" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-esq.jpg"  style="background-repeat:no-repeat">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
    <td background="<?php echo $this->baseUrl (); ?>/images/linha-inf-horiz.jpg" style="background-repeat:repeat-x"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
    <td width="11" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-dir.jpg"  style="background-repeat:no-repeat">
	<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
  </tr>
</table>
	


	<div id="tabela" >
	<!-- class='ui-widget ui-widget-content ui-corner-all' -->
		
	<!--INICIO DA TABELA COM BORDA ARREDONDADAS-->

	<table width="99%" border="0" cellpadding="0" cellspacing="0" style="padding: 0px;">
	  <tr>
	       <td width="5" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-esq.jpg"  style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td background="<?php echo $this->baseUrl (); ?>/images/linha-sup-horiz.jpg" style="background-repeat:repeat-x">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td width="11" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-dir.jpg" style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	  </tr>
	  <tr valign="top">
	       <td valign="top" background="<?php echo $this->baseUrl (); ?>/images/linha-esq-vert.jpg"  style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" /></td>
	   <td class="titulos-miolo">

		<table width="98%" cellpadding="0" cellspacing="0">
				<thead class="ui-widget removedui-widget-header">
				<tr>
				<td width="4%"></td>
				<td colspan="3">
				<div class="titulos-tabela">OPERAÇÕES</div>
				</td>
				</tr>

				<tr class="even">
					<td width="4px"><?php echo $this->myToolbar('operacoes','toptable');?></td>
					<td class="subtitulos-tabela">Descrição</td>
					<td class="subtitulos-tabela" width="70px;">Realiz.</td>
					<td class="subtitulos-tabela" width="40px" align="center"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->operacoes as $operacao){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'operacoes' , 'line', $operacao->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'operacao', 'operacao_id' => $operacao->id ) );?>'>
							<?php echo $operacao->descricao;?>
						</a>
					</div>
					</td>
					<td>
						<?php echo $this->lineProgressbar ( 6, $operacao->id  ); // operação ?>
					</td>
					<td align="center">
						<a href="<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatorioplano', 'operacao_id' => $operacao->id ) );?>">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
			   	<tr>
			   	<td></td>
		       	<td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
		       	</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>

	<!--FIM DA TABELA COM BORDAS ARREDONDADAS-->	</td>
	      <td background="<?php echo $this->baseUrl (); ?>/images/linha-dir-vert.jpg" style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	  </td>
	   </tr>
	   <tr>
	    <td width="5" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-esq.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td background="<?php echo $this->baseUrl (); ?>/images/linha-inf-horiz.jpg" style="background-repeat:repeat-x"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td width="11" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-dir.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	  </tr>
	</table>

	</div>
	
	


</div>