<div class="ui-overlay ui-corner-all">
	<?php // echo $this->planoNavegacao($this->programa) ;
	// echo $this->nivel;
	// echo "<br>";
	?>
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto', 'detalhar'=>($this->nivel=='Projeto')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico, 
													'label'=>'Objetivo Específico', 'nome'=>'objetivo_especifico', 'campo_id'=>'objetivo_especifico_id', 'acao'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico')));?>
		
	</table>
	
	<br></br>

	<br></br>
	<?php if($this->objetivo_especifico){	
		
	?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<br></br>
		<table width='98%'>
			<tr>
			<td></td>
			<td colspan="3">
			<div class="titulos-tabela">METAS</div>
			</td>
			</tr>
			<tr class="even">
					<td width="4%"><?php echo $this->myToolbar('metas','toptable');?></td>
					<td  class="subtitulos-tabela">Descrição</td>
					<td  class="subtitulos-tabela" width="70px">Realiz.</td>
					<td align="center"  width="40px"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
			</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
			<?php
			$select = $this->objetivo_especifico->select();
			$select->order('id'); 
			$loopCount=0;
			foreach ($this->objetivo_especifico->findDependentRowset('Model_Metas',null,$select) as $meta){?>
				<tr class="<?= ($loopCount++%2 ? 'even' : 'odd'); ?>">
					<td>
					<?php echo $this->myToolbar ( 'metas', 'line', $meta->id );	?>
					</td>
					<td >
					<div class="texto-tabela-com-seta">
						<a href=
						'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'meta', 'meta_id' => $meta->id ) );?>'>
						<?php echo $meta->descricao;?>
						</a>
					</div>
					 </td>
					 <td>
					 	<div id="pb-metaacao-<?php echo $meta->id;?>" class="progressbar"></div>
					</td>
					<td  align="center">
						<a href="#">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
			   	<tr>
			   	<td></td>
		       	<td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
		       	</tr>
				 
			<?php }?>
		
		</table>
	</div>
	<?php }?>




</div>