

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget ui-widget-content tb-header '>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>($this->nivel=='ObjetivoEspecifico')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		
	</table>
	
	<br></br>

	<br></br>
	<?php if($this->objetivo_especifico){	
		
	?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header" style="text-align: left">

				<span  style="float:left"> 
					Objetivo Específico: <?php echo $this->objetivo_especifico->descricao;?> 
				</span>
				<span id="pb-objetivo_especifico-<?php echo $acao->id;?>" class="progressbar" style="float:right;width:100px;">
				</span>

			</caption>
			<tbody class="ui-widget ui-widget-content ">
				<tr  class="odd">
					
					<td width='10%'>Estratégias</td>
					<td >
						<ul>
						<?php
						$select = $this->objetivo_especifico->select();
						$select->order('id'); 
						foreach ($this->objetivo_especifico->findDependentRowset('Model_Estrategias',null,$select) as $estrategia){?>
							<li><?php echo $estrategia->descricao;?></li>
						<?php }?>
						</ul>
					</td>					
					
				</tr>
			
			
				
				<tr  class="even" >
					<td>Parcerias</td>

					<td>
						<ul>
						<?php
						$select = $this->objetivo_especifico->select();
						$select->order('id'); 
						foreach ($this->objetivo_especifico->findDependentRowset('Model_Parcerias',null,$select) as $parceria){?>
							<li><?php echo $parceria->descricao;?></li>
						<?php }?>
						</ul>
					</td>
				</tr>
				<tr style="border-bottom: thin solid black" class="odd">
					 <td colspan="2">
					 <?php echo $this->myToolbar('objetivos-especificos','top',$this->objetivo_especifico->id);?>
					 </td>
			 	</tr>
			</tbody>
		</table>
		<br></br>
		<table width='100%'><caption></caption>
			<tr>
				<th nowrap="nowrap" width='2%'>
					
				</th>
				<th>Metas</th>
				<th>%</th>
			</tr>
			<?php
			$select = $this->objetivo_especifico->select();
			$select->order('id'); 
			$loopCount=0;
			foreach ($this->objetivo_especifico->findDependentRowset('Model_Metas',null,$select) as $meta){?>
				<tr class="<?= ($loopCount++%2 ? 'even' : 'odd'); ?>">
					<td>
					<?php echo $this->myToolbar ( 'metas', 'line', $meta->id );	?>
					</td>
					<td >
						<a href=
						'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'meta', 'meta_id' => $meta->id ) );?>'>
						<?php echo $meta->descricao;?>
						</a>
					 </td>
					 <td>
					 	<div id="pb-metaacao-<?php echo $meta->id;?>" class="progressbar"></div>
					</td>
				</tr>
				 
			<?php }?>
		
		</table>
	</div>
	<?php }?>




</div>