

<div class="ui-overlay ui-corner-all">
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'), 
													 'label'=>'Objetivo Específico', 'acao'=>'objetivos-especificos', 
													 'campo_id'=>'objetivo_especifico_id' ));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->operacao,
													 'nome'=>'Operacao', 'label'=>'Operação', 'acao'=>'operacao', 'campo_id'=>'operacao_id', 'detalhar'=>false));?>
	</table>
	
	<br></br>

	<br><br>
	
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<thead class="ui-widget removedui-widget-header">
					<tr class="even">
					<tr>
					<td></td>
					<td colspan="3">
					<div class="titulos-tabela">ATIVIDADES</div>
					</td>
					</tr>

					<td width="4px"><?php echo $this->myToolbar('atividades','toptable');?></td>
					<td  class="subtitulos-tabela">Descrição</td>
					<td  class="subtitulos-tabela" width="70px;">Realiz.</td>
					<td  class="subtitulos-tabela" width="40px" align="center"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>

			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->atividades as $atividade){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'atividades' , 'line', $atividade->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'atividade', 'atividade_id' => $atividade->id ) );?>'>
							<?php echo $atividade->descricao;?>
						</a>
					</div>
					</td>
					<td><div id="pb-atividade-<?php echo $atividade->id;?>" class="progressbar"></div></td>
					<td align="center">
						<a href="#">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
			   	<tr>
			   	<td></td>
		       	<td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
		       	</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>



</div>