

<div class="ui-overlay ui-corner-all">
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>($this->nivel=='Projeto')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->acao,
													 'nome'=>'Acao', 'detalhar'=>($this->nivel=='Acao')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>		
		
	</table>
	
	<br></br>

	<?php if(count($this->atividades)){?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget removedui-widget-header"><b><?php echo strtoupper($this->tableheader);?></b></caption>
			<thead class="ui-widget removedui-widget-header">
				<tr class="odd">
					<td width="40px"><?php echo $this->myToolbar('atividades','toptable');?></td>
					<td >Descrição</td>
					<td width="100px;">Realiz.</td>
					<td align="center">Rel</td>
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->atividades as $atividade){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>" >
					<td class="texto">
						<?php echo $this->myToolbar ( 'atividades' , 'line', $atividade->id  );?>
					</td>
					<td class="texto">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'atividade', 'atividade_id' => $atividade->id ) );?>'>
							<?php echo $atividade->descricao;?>
						</a>
					</td>
					<td width='10px'>
					<div id="pb-atividade-<?php echo $atividade->id;?>" class="progressbar"></div>
					</td>
					<td width='10px'>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>


</div>