

<div>
	<!--   class="ui-overlay ui-corner-all" -->
	<!--INICIO DA TABELA COM BORDA ARREDONDADAS-->

	<table width="99%" border="0" cellpadding="0" cellspacing="0" style="padding: 0px;">
	  <tr>
	       <td width="5" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-esq.jpg"  style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td background="<?php echo $this->baseUrl (); ?>/images/linha-sup-horiz.jpg" style="background-repeat:repeat-x">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td width="11" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-dir.jpg" style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	  </tr>
	  <tr valign="top">
	       <td valign="top" background="<?php echo $this->baseUrl (); ?>/images/linha-esq-vert.jpg"  style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" /></td>
	   <td class="titulos-miolo">


	<table  cellpadding="0" cellspacing="0">
	<!-- class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header' -->
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto',  'detalhar'=>($this->nivel=='Projeto')));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->objetivo_especifico,
													 'nome'=>'objetivos-especificos', 'detalhar'=>($this->nivel=='ObjetivoEspecifico'), 
													 'label'=>'Objetivo Específico', 'acao'=>'objetivos-especificos', 
													 'campo_id'=>'objetivo_especifico_id' ));?>

				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->meta,
													 'nome'=>'Meta', 'acao'=>'meta', 'detalhar'=>false));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->operacao,
													 'nome'=>'Operacao', 'label'=>'Operação', 'acao'=>'operacao', 'campo_id'=>'operacao_id', 'detalhar'=>false));?>
	</table>
	<!--FIM DA TABELA COM BORDAS ARREDONDADAS-->	</td>
	      <td background="<?php echo $this->baseUrl (); ?>/images/linha-dir-vert.jpg" style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	  </td>
	   </tr>
	   <tr>
	    <td width="5" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-esq.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td background="<?php echo $this->baseUrl (); ?>/images/linha-inf-horiz.jpg" style="background-repeat:repeat-x"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td width="11" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-dir.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	  </tr>
	</table>
	

	
	<div id="tabela" >
	<!-- class='ui-widget ui-widget-content ui-corner-all' -->
	<!--INICIO DA TABELA COM BORDA ARREDONDADAS-->

	<table width="99%" border="0" cellpadding="0" cellspacing="0" style="padding: 0px;">
	  <tr>
	       <td width="5" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-esq.jpg"  style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td background="<?php echo $this->baseUrl (); ?>/images/linha-sup-horiz.jpg" style="background-repeat:repeat-x">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	       <td width="11" height="14" background="<?php echo $this->baseUrl (); ?>/images/curva-sup-dir.jpg" style="background-repeat:no-repeat">
		   <img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	   </td>
	  </tr>
	  <tr valign="top">
	       <td valign="top" background="<?php echo $this->baseUrl (); ?>/images/linha-esq-vert.jpg"  style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" /></td>
	   <td class="titulos-miolo">
		
		<table width="100%" cellpadding="0" cellspacing="0">
			<thead class="ui-widget removedui-widget-header">
					<tr class=" ui-state-hover">
					
					<td></td>
					<td colspan="6">
					<div class="titulos-tabela ui-state-hover">ATIVIDADES</div>
					</td>
					</tr>
					<tr class=" ui-state-hover">
					<td width="4px"><?php echo $this->myToolbar('atividades','toptable');?></td>
					<td  class="subtitulos-tabela" width="55%">Descrição</td>
					<td  class="subtitulos-tabela" width="70px;">Data Início</td>
					<td  class="subtitulos-tabela" width="100px;">Data Término</td>
					<td  class="subtitulos-tabela" width="70px;">Valor</td>
					<td  class="subtitulos-tabela" width="70px;">Realiz.</td>
					<td  class="subtitulos-tabela" width="40px" align="center"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				   <tr>
				   <td width="4%"></td>
			       <td colspan="5"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>

			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$cycle=$this->cycle(array('ui-state-default','ui-state-active')); 
				foreach ($this->atividades as $atividade){?>
				<tr class="<?php echo $cycle->next()?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'atividades' , 'line', $atividade->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'atividade', 'atividade_id' => $atividade->id ) );?>'>
							<?php echo $atividade->descricao;?>
						</a>
					</div>
					</td>
					<td class="texto">
						<?php 
						$data =  new Zend_Date($atividade->inicio_data,Zend_Date::ISO_8601);
						echo $data->toString('dd/MM/yyyy');
						?>				
					</td>
					<td class="texto">
						<?php 
						$resultado = $this->atividadeprazo->fetchAll('atividade_id=' . $atividade->id, 'id ASC');
						$prazo = '';
						foreach($resultado as $atividadeprazo){ 
							$prazo =  new Zend_Date($atividadeprazo->prazo_data,Zend_Date::ISO_8601);
						}
						if (!$prazo){
							$prazo =  new Zend_Date($atividade->prazo_data,Zend_Date::ISO_8601);
						}
						echo $prazo->toString('dd/MM/yyyy');
						?>				
					</td>
					<td class="texto">
						<?php echo $atividade->valor;?>
					</td>
					<td>
						<?php echo $this->lineProgressbar ( 7, $atividade->id  ); // atividade ?>
					</td>
					<td align="center">
						<a href="<?php echo $this->url ( array ('controller' => 'relatorios', 'action' => 'relatorioplano', 'atividade_id' => $atividade->id ) );?>">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
			   	<tr>
			   	<td></td>
		       	<td colspan="5"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
		       	</tr>
				<?php 
				}?>
			</tbody>
		</table>

	<!--FIM DA TABELA COM BORDAS ARREDONDADAS-->	</td>
	      <td background="<?php echo $this->baseUrl (); ?>/images/linha-dir-vert.jpg" style="background-repeat:repeat-y">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	  </td>
	   </tr>
	   <tr>
	    <td width="5" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-esq.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td background="<?php echo $this->baseUrl (); ?>/images/linha-inf-horiz.jpg" style="background-repeat:repeat-x"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	    <td width="11" height="11" background="<?php echo $this->baseUrl (); ?>/images/curva-inf-dir.jpg"  style="background-repeat:no-repeat">
		<img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" width="1" height="1" />	</td>
	  </tr>
	</table>


	</div>



</div>