<div class="ui-overlay ui-corner-all">

	<h3>PROGRAMAS</h3>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'><br></br>
		<table width="100%" >
			
			<thead class="ui-widget removedui-widget-header">
				<tr class='odd'>
					<th nowrap="nowrap">
						<?php echo $this->myToolbar ( 'programas', 'toptable' );?>
					</th>
					<th>Descrição</th>
					<th>Realiz.</th>
					<th>Relatório</th>
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0;
				foreach ( $this->programas as $programa ) {
					?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td >
						<?php
						echo $this->myToolbar ( 'programas', 'line', $programa->id );
						?>
					</td>
					<td class="texto">
						<a
							href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'programa', 'programa_id' => $programa->id ) );?>'>
							<?php echo $programa->descricao;?>
						</a>
					</td>
					<td>
					<div id="pb-programa-<?php echo $programa->id;?>" class="progressbar">
					
					</div>
					</td>
					<td>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a> 
					</td>
					</tr>
				<?php
				$loopCount++;
				}
				?>
			</tbody>
		</table>
		<br></br>
	</div>
</div>

