

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget-header ui-state-highlight'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		
		<?php
			if($this->nivel=='Projeto') 
				echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>($this->nivel=='Projeto')));
		echo "opção de adicionar subprojeto"		
		?>
		
	</table>
	<br></br>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header"><?php echo strtoupper($this->tableheader);?></caption>
			<thead class="ui-widget ui-widget-header">
				<td width="40px"><?php echo $this->myToolbar('projetos','toptable');?></td>
				<td class="ui-widget ui-widget-header">Descrição</td>
				<td>Realiz.</td>
				<td></td>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php foreach ($this->projetos as $projeto){?>
				<tr >
					<td class="texto">
						<?php echo $this->myToolbar ( 'projetos' , 'line', $projeto->id  );?>
					</td>
					<td class="texto"><?php echo $projeto->descricao;?></td>
					<td></td>
					<td>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php }?>
			</tbody>
		</table>
		<br></br>
	</div>
</div>