

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget-header ui-state-highlight'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
		<tr>
		<td colspan="2" height="2px" style="background-color:black"></td>
		</tr>
		
		<?php
			if($this->nivel=='Projeto') 
				echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'detalhar'=>true));
		?>
		
	</table>
	
	<br></br>
	<?php if(count($this->projetos)){?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header"><?php echo strtoupper($this->tableheader);?></caption>
			<thead class="ui-widget ui-widget-header">
				<tr>
					<td width="40px"><?php echo $this->myToolbar('projetos','toptable');?></td>
					<td class="ui-widget ui-widget-header">Descrição</td>
					<td width="100px;">Realiz.</td>
					<td align="center">Rel</td>
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->projetos as $projeto){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>" >
					<td class="texto">
						<?php echo $this->myToolbar ( 'projetos' , 'line', $projeto->id  );?>
					</td>
					<td class="texto">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'projeto', 'projeto_id' => $projeto->id ) );?>'>
							<?php echo $projeto->descricao;?>
						</a>
					</td>
					<td width='10px'>
					<div id="pb-projeto-<?php echo $projeto->id;?>" class="progressbar"></div>
					</td>
					<td width='10px'>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>





	<br></br>
	<?php if(count($this->acoes)){?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header">Ações</caption>
			<thead class="ui-widget ui-widget-header">
				<tr>
					<td width="40px"><?php echo $this->myToolbar('acoes','toptable');?></td>
					<td class="ui-widget ui-widget-header">Descrição</td>
					<td width="100px;">Realiz.</td>
					<td>Relat.</td>
				</tr>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->acoes as $acao){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto">
						<?php echo $this->myToolbar ( 'acoes' , 'line', $acao->id  );?>
					</td>
					<td class="texto">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'acao', 'acao_id' => $acao->id ) );?>'>
							<?php echo $acao->descricao;?>
						</a>
					</td>
					<td width='10px'><div id="pb-acao-<?php echo $acao->id;?>" class="progressbar"></div></td>
					<td width='10px'>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>




</div>