<div class="ui-overlay ui-corner-all">
	<?php // echo $this->planoNavegacao($this->programa) ;?>
	<table  class='ui-widget ui-widget-content ui-corner-all removedui-state-highlight tb-header'>
		<?php echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->programa,
													 'nome'=>'Programa', 'acao'=>'Programa', 'detalhar'=>($this->nivel=='Programa')));?>
				 <tr>
			       <td colspan="2"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
		
		<?php
			if($this->nivel=='Projeto') 
				echo $this->partial('plano/cabecalho.phtml',array('objeto'=>$this->projeto,
													 'nome'=>'Projeto', 'acao'=>'Projeto', 'detalhar'=>true));
		?>
		
	</table>
	
	<br></br>
	<?php if(count($this->projetos)){?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="98%">
			<thead class="ui-widget removedui-widget-header">
				<tr>
				<td></td>
				<td colspan="3">
				<div class="titulos-tabela"><?php echo strtoupper($this->tableheader);?></div>
				</td>
				</tr>

				<tr class="even">
					<td><?php echo $this->myToolbar('projetos','toptable');?></td>
					<td  class="subtitulos-tabela">Descrição</td>
					<td  class="subtitulos-tabela" width="70px">Realiz.</td>
					<td align="center"  width="40px"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				 <tr>
			       <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->projetos as $projeto){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>" >
					<td class="texto"  width="4%">
						<?php echo $this->myToolbar ( 'projetos' , 'line', $projeto->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'projeto', 'projeto_id' => $projeto->id ) );?>'>
							<?php echo $projeto->descricao;?>
						</a>
					</div>
					</td>
					<td align="center">
					<div id="pb-projeto-<?php echo $projeto->id;?>" class="progressbar"></div>
					</td>
					<td  align="center">
						<a href="#">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>





	<br></br>
	<?php if(count($this->objetivos_especificos)){?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<thead class="ui-widget removedui-widget-header">
				<tr>
				<td></td>
				<td colspan="3">
				<div class="titulos-tabela">OBJETIVOS ESPECÍFICOS</div>
				</td>
				</tr>
				<tr class="even">
					<td width="40px"><?php echo $this->myToolbar('acoes','toptable');?></td>
					<td class="subtitulos-tabela" >Descrição</td>
					<td class="subtitulos-tabela" width="70px">Realiz.</td>
					<td class="subtitulos-tabela"  style="text-align:center" width="40px"><img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif"></td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php
				$loopCount=0; 
				foreach ($this->objetivos_especificos as $objetivos_especificos){?>
				<tr class="<?= ($loopCount%2 ? 'odd' : 'even'); ?>">
					<td class="texto"  width="4%">
						<?php echo $this->myToolbar ( 'objetivos-especificos' , 'line', $objetivos_especificos->id  );?>
					</td>
					<td>
					<div class="texto-tabela-com-seta">
						<a href=
							'<?php echo $this->url ( array ('controller' => 'plano', 'action' => 'objetivos-especificos', 'objetivo_especifico_id' => $objetivos_especificos->id ) );?>'>
							<?php echo $objetivos_especificos->descricao;?>
						</a>
					</div>
					</td>
					<td align="center"><div id="pb-acao-<?php echo $objetivos_especificos->id;?>" class="progressbar"></div></td>
					<td align="center">
						<a href="#">
							<img alt="" src="<?php echo $this->baseUrl (); ?>/images/impressora-miolo.gif" border="0">
						</a> 
					</td>
				</tr>
				   <tr>
				   <td></td>
			       <td colspan="3"><div class="linha-abaixo-texto"><img src="<?php echo $this->baseUrl (); ?>/images/1x1.gif" /></div></td>
			       </tr>
				
				<?php
				$loopCount++; 
				}?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>




</div>