

<div class="ui-overlay ui-corner-all">
	<?php// echo $this->planoNavegacao($this->programa) ;?>
	<table class='ui-widget-header ui-state-highlight'>
		<tr>
			<td class='ui-widget-header '>Programa</td>
			<td class='ui-state-highlight' style='padding-left:15px'><?php echo $this->programa->descricao?></td>
		</tr>
		<tr>
			<td class='ui-widget-header '>Projeto</td>
			<td class='ui-state-highlight' style='padding-left:15px'><?php echo $this->projeto->descricao?></td>
		</tr>		
		<tr>	
			<td class='ui-widget-header' >Objetivos do Projeto</td>
			<td class='ui-state-highlight' style='padding-left:15px'>
			<?php 
				foreach($this->projeto->findDependentRowset('Model_ObjetivosProjeto') as $objetivo){
					echo '<li>'.$objetivo->descricao.'</li>';
				}
			?>
			
			</td>
		</tr>
		<tr>	
			<td class='ui-widget-header' >Metas do programa</td>
			<td class='ui-state-highlight' style='padding-left:15px'>
			<?php 
				foreach($this->projeto->findDependentRowset('Model_MetasProjeto') as $meta){
					echo '<li>'.$meta->descricao.'</li>';
				}
			?>
			
			</td>
		</tr>
	</table>
	<br></br>
	<?php
		$this->projetos = $this->projeto->findDependentRowset('Model_Projetos');
		if($this->projetos){ 
	?>
	<div id="tabela" class='ui-widget ui-widget-content ui-corner-all'>
		
		<table width="100%">
			<caption class="text-caption ui-widget ui-widget-header">PROJETOS</caption>
			<thead class="ui-widget ui-widget-header">
				<td width="40px"><?php echo $this->myToolbar('projetos','toptable');?></td>
				<td class="ui-widget ui-widget-header">Descrição</td>
				<td>Realiz.</td>
				<td></td>
			</thead>
			<tbody class="ui-widget ui-widget-content ">
				<?php foreach ($this->projetos as $projeto){?>
				<tr >
					<td class="texto">
						<?php echo $this->myToolbar ( 'projetos' , 'line', $projeto->id  );?>
					</td>
					<td class="texto"><?php echo $projeto->descricao;?></td>
					<td></td>
					<td>
						<a href="#" class="my-button ui-state-default ui-corner-all">
							<span class="ui-icon ui-icon-print">relatório</span>
						</a>
					</td>
				</tr>
				<?php }?>
			</tbody>
		</table>
		<br></br>
	</div>
	<?php }?>
</div>