

<div class="outer">
<?php echo $this->myToolbar('projetos','top');?>
<?php echo $this->planoNavegacao($this->programa) ;?>
<div id="tabela" class='inner'>
<br></br>
<table width="100%">
<caption class="titulos-tabela">Projetos</caption>
<thead class="titulos-tabela">
<th></th>
<th>Descrição</th>
<th>Realiz.</th>
<th>Relatório</th>
</thead>
<tbody>
	<?php foreach ($this->projetos as $projeto){?>
	<tr bgcolor="#ece9d8">
		<td class="texto"><?php echo $this->myToolbar('projetos','line',$projeto->id);?></td>
		<td class="texto"><?php echo $projeto->descricao;?></td>
		<td></td>
		<td><img alt="relatório" src="<?php echo $this->baseUrl();?>/images/impressora.gif"/> </td>
	</tr>
	<?php }?>
</tbody>
</table>
<br></br>
</div>
</div>