<ul id='grp_menu_0' class="navigation filetree">

<?php

$html = array();
$ix=0;
$ixgrp=0;
foreach ($this->container as $page) 
{
	$ix++;
    $html[] = "<li id='menu_$ix'><span class='folder'>";
    $html[] = $this->menu()->htmlify($page) . PHP_EOL."</span>";

    if (!empty($page->pages))
    {
		$ixgrp++;
        $html[] = "<ul  id='grp_menu_$ixgrp'>";
        foreach ($page->pages as $subpage) 
        {
        	$ix++;	
            $html[] = "<li id='menu_$ix'><span class='folder' >";
            $html[] = $this->menu()->htmlify($subpage)."</span>" . PHP_EOL;
                if (!empty($subpage->pages))
			    {
					$ixgrp++;
			        $html[] = "<ul  id='grp_menu_$ixgrp'>";
			        foreach ($subpage->pages as $subpage1) 
			        {
			        	$ix++;	
			            $html[] = "<li id='menu_$ix'><span class='folder' >";
			            $html[] = $this->menu()->htmlify($subpage1)."</span>" . PHP_EOL;
			            
					    if (!empty($subpage1->pages))
					    {
							$ixgrp++;
					        $html[] = "<ul  id='grp_menu_$ixgrp'>";
					        foreach ($subpage1->pages as $subpage2) 
					        {
					        	$ix++;	
					            $html[] = "<li id='menu_$ix'><span class='folder' >";
					            $html[] = $this->menu()->htmlify($subpage2)."</span>" . PHP_EOL;
					            
						        if (!empty($subpage2->pages))
							    {
									$ixgrp++;
							        $html[] = "<ul  id='grp_menu_$ixgrp'>";
							        foreach ($subpage2->pages as $subpage3) 
							        {
							        	$ix++;	
							            $html[] = "<li id='menu_$ix'><span class='file' >";
							            $html[] = $this->menu()->htmlify($subpage3) . PHP_EOL;
							        }
							        $html[] = "</ul>";
							    }					            
					            
					            
					        }
					        $html[] = "</ul>";
					    }
								            
			            
			        }
			        $html[] = "</ul>";
			    }
			            
        }
        $html[] = "</ul>";
    }

    $html[] = "</li>";
}

echo join(PHP_EOL, $html);

?>
</ul>








































