<?php echo $this->doctype ( 'XHTML1_TRANSITIONAL' );?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
$mysession = new Zend_Session_Namespace ( 'temas' );
$tema =	'custom-theme' ;
$this->jQuery ()->enable ();

if ($this->jQuery ()->isEnabled ()) {
	$this->jQuery ()->setLocalPath ( $this->baseUrl () . '/js/jquery.js' )->setUiLocalPath ( $this->baseUrl () . '/js/jquery-ui.js' )
	->addStylesheet ( $this->baseUrl () . '/css/'.$tema.'/jquery-ui-1.7.2.custom.css' );
}
/**
 * ZendX_JQuery_View_Helper_JQuery_Container $this->JQuery()
 */
$this->JQuery ()->addJavascriptFile ( $this->baseUrl () . '/js/jquery-ui.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.bgiframe.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.dimensions.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.positionBy.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.corner.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.form.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/ui.datepicker-pt-BR.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/grid.locale-pt-br.js')				
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.jqGrid.min.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.tooltip.pack.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/myscripts.js' )
				->addStylesheet ( $this->baseUrl () . '/css/jquery.jdMenu.css' );

echo $this->JQuery ();

/*
 * ckeditor para ajudas.
 */
if ( !$this->ckeditor ) { 
	echo $this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
}



?> 
<?php echo $this->headMeta ();?>
<?php echo $this->headTitle ();?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/site.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/ui.jqgrid.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery.tooltip.css' );?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/print.css" media="print" />

<!--[if IE]>
<style type="text/css" media="screen">
body {
behavior: url(<?php echo $this->baseUrl ();?>/css/csshover.htc); /* call hover behaviour file */
} 
#menu1 ul li {
float: left; /* cure IE5.x "whitespace in lists" problem */
width: 100%;
}
#menu1 ul li a {
height: 1%; /* make links honour display: block; properly */
} 
 
#menu1 a, #menu1 h2 {
font: bold 0.7em/1.4em arial, helvetica, sans-serif; 
/* if required use em's for IE as it won't resize pixels */
} 

.ui-widget{
    font-size: 1.1em;
}
#menu1 ul li{
 font-size:13px !important;
}
</style>
<![endif]-->


<style type="text/css">
@import url("<?php
echo $this->baseUrl ();
?>/css/nao-ie.css") all;
</style>
</head>
<body>
	<div id="topo" >
		<div id="topo-portal">

			<iframe width="100%" scrolling="no" height="50" frameborder="0" align="middle" target="_blank" src="http://portal.saude.sp.gov.br/barra-gov/barra.htm">
			</iframe>

		</div>
		<div id="topo-ico" style="float:left">
			<img class="topo-logo" alt="" src="<?php echo $this->baseUrl (); ?>/images/titulo_ses.jpg"/>
			<div style="float:left; padding-left: 80px;" class="titulo" >
				<font size="4"><b>Programação Anual de Saúde - PAS-E 2010</b></font>
			</div>
		</div>
		<div id="topo-buttons" style="position: absolute; top: 100px; right: 55px; width: 115px;" >
			<?php 
			echo "<a href='".$this->url(array('controller'=>'favoritos','action'=>'add')) ."'
								title='Adicionar Favorito'> 
								<img alt='Adicionar Marcador' src='". $this->baseUrl() ."/images/addbookmark.jpg' width='23' height='23' border='0'/></a>";								
			?>
			&nbsp;&nbsp;
			<?php 
			echo "<a href='".$this->url(array('controller'=>'favoritos','action'=>'list')) ."'
								title='Visualizar Marcadores'> 
								<img alt='Visualizar Marcadores' src='". $this->baseUrl() ."/images/seebookmark.jpg' width='23' height='23' border='0'/></a>";								
			?>
			&nbsp;&nbsp;
			<?php echo $this->myTooltip(); ?>
		</div>
		<div style="position: absolute; top: 100px; left: 15px; width: 800px;" >
			<font size="1">
			<?php
			echo $this->navigation ()->breadcrumbs ()->setMinDepth ( 0 )->setLinkLast ( true )->setSeparator ( " : " );
			?>
			</font>
		</div>
		
		<br/>
		
	</div>
	
	<div id="corpo" class="ui-widget ui-corner-all">
	
	<h3><?php
	echo $this->escape ( $this->title );
	?></h3>
		<?php
		echo $this->layout ()->content;
		?>
		
	
	</div>
	 
	<div id="menu1">
	 
	<div id="barra" class='menu-barra ui-widget ui-widget-header '>
		<div class="ui-state-default ui-corner-all" style="text-align:center">
			<span class="ui-icon ui-icon-home">menu</span>
			<font size="1">M<br>E<br>N<br>U<br></font>
		</div> 
	</div>
	 
	<div style="float: left;">
		<ul>
			<?php
			echo $this->navigation ()->menu ()->setUlClass ( 'esconder' )->setMaxDepth(2);
			?>
		</ul>
	</div>
	
	</div>
 	
</body>
</html>
