<?php echo $this->doctype ( 'XHTML1_TRANSITIONAL' );?>
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    	<style>
	.ui-button { margin-left: -1px; }
	.ui-button-icon-only .ui-button-text { padding: 0.35em; } 
	.ui-autocomplete-input { margin: 0; padding: 0.48em 0 0.47em 0.45em; }
	</style>

<script type="text/javascript">
    var baseUrl = '<?php echo $this->baseUrl ()?>'
</script>
<?php
$mysession = new Zend_Session_Namespace ( 'temas' );
$tema =	'custom-theme' ;
$this->jQuery ()->enable ();

if ($this->jQuery ()->isEnabled ()) {
	$this->jQuery ()->setLocalPath ( $this->baseUrl () . '/js/jquery-1.4.4.min.js' )->setUiLocalPath ( $this->baseUrl () . '/js/jquery-ui.js' )
	->addStylesheet ( $this->baseUrl () . '/css/'.$tema.'/jquery-ui-1.8.7.custom.css' );
}
/**
 * ZendX_JQuery_View_Helper_JQuery_Container $this->JQuery()
 */
$this->JQuery ()->addJavascriptFile ( $this->baseUrl () . '/js/jquery-ui-1.8.7.custom.min.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.bgiframe.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/ui.datepicker-pt-BR.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/grid.locale-pt-br.js')				
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.jqGrid.min.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.tooltip.pack.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.cookie.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.jstree.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.contextmenu.js')
                                ->addJavascriptFile ( $this->baseUrl () . '/js/jsgantt.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/myscripts.js' );

echo $this->JQuery ();
/*
 * ckeditor para ajudas.
 */
if ( !$this->ckeditor ) { 
	//echo $this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
}

?> 
<?php echo $this->headMeta ();?>
<?php echo $this->headTitle ();?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/site.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/ui.jqgrid.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery.tooltip.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jqModal.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery.treeview.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jsgantt.css' );?>
    


<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/print.css" media="print" />



<!--[if IE]>
<style type="text/css" media="screen">
body {
behavior: url(<?php echo $this->baseUrl ();?>/css/csshover.htc); /* call hover behaviour file */
} 
#menu1 ul li {
float: left; /* cure IE5.x "whitespace in lists" problem */
width: 100%;
}
#menu1 ul li a {
height: 1%; /* make links honour display: block; properly */
} 
 
#menu1 a, #menu1 h2 {
font: bold 0.7em/1.4em arial, helvetica, sans-serif; 
/* if required use em's for IE as it won't resize pixels */
} 

.ui-widget{
    font-size: 1.1em;
}
.ui-widget .ui-widget{
    font-size: 1em;
}
#menu1 ul li{
 font-size:13px !important;
}
</style>
<![endif]-->

<style type="text/css">
@import url("<?php
echo $this->baseUrl ();
?>/css/nao-ie.css") all;
</style>

</head>
<body>
	<div id="topo" >
		<div id="topo-ico" style="float:left;clear: both">
			<img class="topo-logo" alt="" src="<?php echo $this->baseUrl (); ?>/images/titulo_ses.jpg"/>
			<div style="float:left; padding-left: 80px; font-size: 1.5em; font-weight: bold" class="titulo" >
			 	 Programação Anual de Saúde - PAS-E 2011 
			</div>
                        <div style='text-align:center; clear: both'><span id='flash-m'></span></div>
		</div>

		<div  style="float: left; width: 800px; font-size: 0.9em" >
                    <table style="width: 100%">
                        <tr>
                            <td style="width: 30%">
                                
                            </td>
                            <td>
                                <?php
                                echo $this->navigation ()->breadcrumbs ()->setMinDepth ( 0 )->setLinkLast ( true )->setSeparator ( " : " );
                                ?>
                            </td>
                        </tr>

                    </table>
		</div>
	</div>
    <table width="100%" style="clear: both">
	  <tr>
	    <td style='min-width:200px;max-width:200px; min-height: 300px;width: 200px;'>
                <div style="overflow:   hidden;height: 100%; width: 100%">
                        <table class="borda-arredondada">
                          <tr class="top">
                              <td class="tb-corner tb-corner-top-left" width="5px">
                               </td>
                               <td class="tb-corner tb-corner-top-center" height="14px">
                               </td>
                               <td class="tb-corner tb-corner-top-right" >
                               </td>
                          </tr>
                          <tr class="tb-corner-side">
                               <td class="tb-corner-side-left-menu titulos-miolo" colspan="2" height="400px" style="min-width: 170px;width: 180px" >
                                   <?php echo $this->partial('_login.phtml')?>
                                   <hr></hr>
                                   <div id='menu_tree' style="overflow-x: hidden;min-height: 280px; margin-top: 10px">
                                    </div>
                               </td>
                              <td class="tb-corner-side-right" ></td>
                          </tr>
                          <tr>
                              <td class="tb-corner-botton-left" height="11px">
                              </td>
                              <td class="tb-corner-botton-center" >
                                    </td>
                              <td class="tb-corner-botton-right"></td>
                          </tr>
                        </table>
                </div>
            </td>
            <td style='min-width:580px;width:90%'>
                <div id="corpo" style="width: 100%;height: 100%">
                        <table class="borda-arredondada">
                          <tr class="top">
                              <td class="tb-corner tb-corner-top-left" width="5px">
                               </td>
                               <td class="tb-corner tb-corner-top-center" height="14px">
                               </td>
                               <td class="tb-corner tb-corner-top-right" >
                               </td>
                          </tr>
                          <tr class="tb-corner-side">
                               <td class="tb-corner-side-left">
                               </td>
                               <td class="titulos-miolo" height="400px">
                                   
                                    <?php
                                    echo $this->layout ()->content;
                                    ?>
                               </td>
                              <td class="tb-corner-side-right" ></td>
                          </tr>
                          <tr>
                              <td class="tb-corner-botton-left" height="11px">
                              </td>
                              <td class="tb-corner-botton-center" >
                                    </td>
                              <td class="tb-corner-botton-right"></td>
                          </tr>
                        </table>
                </div>
            </td>
          </tr>
	</table>
	<div id='formulario_ajax'></div>
</body>

</html>


