<?php echo $this->doctype ( 'XHTML1_TRANSITIONAL' );?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php
$mysession = new Zend_Session_Namespace ( 'temas' );
$tema =	'custom-theme' ;
$this->jQuery ()->enable ();

if ($this->jQuery ()->isEnabled ()) {
	$this->jQuery ()->setLocalPath ( $this->baseUrl () . '/js/jquery.js' )->setUiLocalPath ( $this->baseUrl () . '/js/jquery-ui.js' )
	->addStylesheet ( $this->baseUrl () . '/css/'.$tema.'/jquery-ui-1.7.2.custom.css' );
}
/**
 * ZendX_JQuery_View_Helper_JQuery_Container $this->JQuery()
 */
$this->JQuery ()->addJavascriptFile ( $this->baseUrl () . '/js/jquery-ui.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.bgiframe.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.dimensions.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.positionBy.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.corner.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.form.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.jqModal.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/ui.datepicker-pt-BR.js' )
				->addJavascriptFile ( $this->baseUrl () . '/js/grid.locale-pt-br.js')				
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.jqGrid.min.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.tooltip.pack.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.hotkeys.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.cookie.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/jquery.treeview.js')
				->addJavascriptFile ( $this->baseUrl () . '/js/myscripts.js' )
				
				->addStylesheet ( $this->baseUrl () . '/css/jquery.jdMenu.css' );

echo $this->JQuery ();

/*
 * ckeditor para ajudas.
 */
if ( !$this->ckeditor ) { 
	echo $this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
}



?> 
<?php echo $this->headMeta ();?>
<?php echo $this->headTitle ();?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/site.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/ui.jqgrid.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery.tooltip.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jqModal.css' );?>
<?php echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery.treeview.css' );?>


<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/css/print.css" media="print" />

<style type="text/css">
@import url("<?php
echo $this->baseUrl ();
?>/css/nao-ie.css") all;
</style>
</head>
<body>
	<div id="topo" >
		<div id="topo-portal">
		<!-- 
			<iframe width="100%" scrolling="no" height="50" frameborder="0" align="middle" target="_blank" src="http://portal.saude.sp.gov.br/barra-gov/barra.htm">
			</iframe>
		-->
		</div>
		<div id="topo-ico" style="float:left">
			<img class="topo-logo" alt="" src="<?php echo $this->baseUrl (); ?>/images/titulo_ses.jpg"/>
			<div style="float:left; padding-left: 80px;" class="titulo" >
				<font size="4"><b>Programação Anual de Saúde - PAS-E 2010</b></font>
			</div>
		</div>
		<div id="topo-buttons" style="position: absolute; top: 100px; right: 55px; width: 115px;" >
			<?php 
			echo "<a href='".$this->url(array('controller'=>'favoritos','action'=>'add')) ."'
								title='Adicionar Favorito'> 
								<img alt='Adicionar Marcador' src='". $this->baseUrl() ."/images/addbookmark.jpg' width='23' height='23' border='0'/></a>";								
			?>
			&nbsp;&nbsp;
			<?php 
			echo "<a href='".$this->url(array('controller'=>'favoritos','action'=>'list')) ."'
								title='Visualizar Marcadores'> 
								<img alt='Visualizar Marcadores' src='". $this->baseUrl() ."/images/seebookmark.jpg' width='23' height='23' border='0'/></a>";								
			?>
			&nbsp;&nbsp;
			<?php echo $this->myTooltip(); ?>
		</div>
		<div  style="position: absolute; top: 100px; left: 15px; width: 800px;" >
			<font size="1">
			<?php
			echo $this->navigation ()->breadcrumbs ()->setMinDepth ( 0 )->setLinkLast ( true )->setSeparator ( " : " );
			?>
			</font>
		</div>
		
		<br/>
		
	</div>
	<table>
	  <tr>
	    <td style='min-width:210px;'>
	      
			<div  style="float: left;margin-top:30px;min-height: 200px " class="ui-widget ui-widget-content ui-corner-all">
				<div id='menu_tree'>
					<?php
					$partial = array('_navtree.phtml', 'default');
					$this->navigation()->menu()->setPartial($partial);
					echo $this->navigation ()->menu ();
					?>
				</div>	
			</div>
		</td>
		<td style='max-width:580px;'>
			<div id="corpo" class="ui-widget ui-corner-all" style="float: left;">
			
			<h3><?php
			echo $this->escape ( $this->title );
			?></h3>
				<?php
				echo $this->layout ()->content;
				?>
			</div>
		</td>
      </tr>
	</table>
</body>
</html>


